const newsData = 
[
    {
        "testata": "ANSA",
        "lingua_originale": "it",
        "titolo_orig": "Ridotto del 90% il traffico di petroliere nello stretto di Hormuz",
        "testo_it": "Crollo del 90% per il traffico di petroliere nello stretto di Hormuz.",
        "priorita": "Alta",
        "id_gruppo": 2,
        "link": "https://www.ansa.it/sito/notizie/mondo/mediooriente/2026/03/04/ridotto-del-90-il-traffico-di-petroliere-nello-stretto-di-hormuz_0725298f-110f-460f-af21-cd39a550928c.html",
        "orario": "15:37",
        "timestamp": 1772635038.0,
        "contenuto_esteso": "Lo afferma la società di intelligence del mercato energetico Kpler"
    },
    {
        "testata": "ANSA",
        "lingua_originale": "it",
        "titolo_orig": "Fonte Ankara, 'Turchia non era obiettivo del missile iraniano ma base a Cipro'",
        "testo_it": "Ankara: il missile iraniano mirava a una base a Cipro, non alla Turchia.",
        "priorita": "Alta",
        "id_gruppo": 3,
        "link": "https://www.ansa.it/sito/notizie/mondo/mediooriente/2026/03/04/fonte-ankara-turchia-non-era-obiettivo-del-missile-iraniano-ma-base_619fc46e-e87f-480e-8819-4d3ff536e764.html",
        "orario": "13:23",
        "timestamp": 1772626983.0,
        "contenuto_esteso": "'Riteniamo che mirasse a una base dell'isola e abbia deviato'"
    },
    {
        "testata": "AGI",
        "lingua_originale": "it",
        "titolo_orig": "Rozzo e lento, il micidiale drone iraniano Shahed-136",
        "testo_it": "Analisi tecnica: l'efficacia del drone iraniano Shahed-136 nel conflitto.",
        "priorita": "Bassa",
        "id_gruppo": 4,
        "link": "https://www.agi.it/estero/news/2026-03-04/iran-il-micidiale-drone-shahed-35941077/",
        "orario": "18:34",
        "timestamp": 1772645677.0,
        "contenuto_esteso": "AGI - È rozzo, è lento e forse proprio per questo è micidiale. È il drone Shahed-136 , assurto agli onori della guerra grazie al massiccio impiego sul teatro ucraino da parte dell' esercito russo , ma soprattutto fiore all'occhiello dell'autarchica industria bellica iraniana . I pasdaran ne hanno mostrato tunnel pieni in un video diventato virale e per fare sfoggio della capacità offensiva della Repubblica islamica . Prodotto dalla Iran Aircraft Manufacturing Industrial Company (azienda sottoposta alle sanzioni statunitensi ), lo Shahed-136 è un piccolo veicolo aereo a pilotaggio remoto che, di solito in formazioni di due, esplode all'impatto con il bersaglio e per questo viene chiamato drone \"kamikaze\" . Lungo 3,5 metri, ha un'apertura alare di 2,5 metri e una velocità massima di 185 chilometri orari . Secondo il ministero della Difesa britannico ha una portata di 2.500 chilometri . Lo Shahed ha una fusoliera a forma di delta, che può trasportare una testata di 36 chilogrammi . Vola principalmente a bassa quota ed è raramente rilevabile dai radar . Si alza in volo su una struttura che permette il dispiegamento in sequenza fino a cinque velivoli. Il lancio è di tipo assistito a razzo , al quale subentra il motore convenzionale una volta che il drone ha raggiunto la quota prestabilita. Rumorosi, economici, adatti a un uso massiccio con lanci a raffica , i droni Shahed-136 sono in competizione con i Bayraktar TB2 , forniti dalla Turchia all' Ucraina , più veloci e sofisticati, determinanti nei primi giorni degli scontri. Limiti e capacità di attacco Secondo Justin Bronk, senior fellow del think tank britannico Royal United Services Institute, \"lo Shahed-136 offre un modo relativamente economico di sferrare attacchi a lungo raggio su obiettivi fissi . La navigazione e la precisione di Shahed si basano su sistemi GPS commerciali e la sua capacità di carico ne limita le capacità di attacco . Inoltre manca della capacità di colpire bersagli mobili e ha meccanismi di difesa minimi contro i sistemi anti-UAV . I droni Shahed-136 sono entrati ufficialmente in servizio in Iran nel 2021 , ma secondo diverse fonti erano già operativi nel 2020 nello Yemen ."
    },
    {
        "testata": "AGI",
        "lingua_originale": "it",
        "titolo_orig": "Bloccati a Dubai per la crisi in Iran. La paura e il rientro: \"La Farnesina non ci ha mai ...",
        "testo_it": "Crisi Iran: turisti bloccati a Dubai denunciano l'assenza della Farnesina.",
        "priorita": "Bassa",
        "id_gruppo": 5,
        "link": "https://www.agi.it/estero/news/2026-03-04/dubai-sirene-italiani-35938453/",
        "orario": "18:17",
        "timestamp": 1772644653.0,
        "contenuto_esteso": "AGI - Le valigie erano pronte, l’aeroporto a un passo. Poi la notizia dei voli cancellati e dello spazio aereo chiuso ha trasformato un rientro programmato nei cinque giorni più lunghi della loro vita. A Dubai , quasi 200 ragazzi – la maggior parte minorenni – arrivati il 21 febbraio per il progetto “ Ambasciatori del Futuro ” di Wsc Italia , si sono trovati nel mezzo di una crisi internazionale improvvisa . A coordinarli lì, Selene Piazzoli, responsabile del gruppo durante il viaggio, insieme alla macchina istituzionale della Farnesina . L'inizio della crisi Tutto comincia sabato mattina, con la comunicazione della chiusura preventiva dello spazio aereo dopo l’escalation tra Stati Uniti, Israele e Iran . Gli allarmi sui cellulari squillano all’unisono. I ragazzi, 16 e 17 anni, si guardano negli occhi. “Il primo momento è stato di paura – racconta Piazzoli – soprattutto quando i telefoni hanno iniziato a suonare”. Due volte il gruppo viene fatto scendere nei bunker dell’hotel , per brevi verifiche di sicurezza. Intanto, si apre l’ emergenza logistica : hotel pieni , camere da liberare, gruppi da dividere temporaneamente in strutture dotate di rifugi . Ma fin dalle prime ore, accanto all’organizzazione interna, si attiva la rete diplomatica italiana . La rete della Farnesina in campo “Non siamo mai stati soli”, ripete più volte Piazzoli. L’ ambasciatore ad Abu Dhabi e il console generale a Dubai si recano personalmente a verificare le condizioni del gruppo. La Farnesina , attraverso l’ Unità di crisi , mantiene un contatto costante con i referenti sul posto e con le famiglie in Italia . Viene attivata una task force su indicazione del ministro Antonio Tajani . Il lavoro è continuo: monitoraggio della situazione di sicurezza , interlocuzione con le autorità emiratine , valutazione delle opzioni di rientro alternative , aggiornamenti costanti ai genitori. “Non era semplice – spiega Piazzoli – ma sono stati perfetti. Hanno lavorato senza sosta per riportarci a casa ”. Tra il primo e il due marzo si sentono i primi rimbombi : missili e droni intercettati nei cieli degli Emirati. La tensione sale . Per i ragazzi, che pochi giorni prima simulavano il lavoro dei diplomatici, l’emergenza diventa esperienza diretta . “Hanno visto cosa significa davvero essere console o ambasciatore nei momenti peggiori: responsabilità , pressione , famiglie in attesa di notizie”. Il coordinamento per il rientro Anche per le famiglie in Italia sono giorni sospesi. Giuseppe Vella, padre di Chiara, 17 anni, parla di “quattro-cinque giorni che valgono anni”. Chiara aveva compiuto 17 anni proprio a Dubai , il 27 febbraio e il giorno dopo avrebbe dovuto prendere l'aereo per tornare in Italia. \"Erano in hotel con le valigie pronte quando è arrivata la notizia di quanto stava accadendo in Iran . All'inizio sembrava quasi irreale, con i ragazzi che pensavano fosse un imprevisto da poco, magari un giorno di vacanza in più'\". Poi le immagini in tv, i missili nel cielo , gli allarmi. \"Ho fatto videochiamate in cui vedevo ragazzi piangere e abbracciarsi. Mia figlia mi ha scritto: 'Papà, ti amo'. Sono stati momenti di forte tensione \". In quelle ore, racconta, la comunicazione è costante . Da un lato Wsc, dall’altro la Farnesina . L’ Unità di crisi aggiorna, rassicura, spiega scenari e alternative. Il primo piano prevede un trasferimento via terra verso l’Oman , quattro o cinque ore di viaggio, ma il tragitto presenta criticità. Si lavora quindi a una soluzione alternativa : partenza da Abu Dhabi con un volo organizzato grazie al coordinamento del governo italiano e alla mediazione diplomatica con le autorità locali. “Quando abbiamo saputo che l’aereo era decollato, abbiamo tirato un sospiro di sollievo ”. All’arrivo a Malpensa , lacrime e abbracci . “Voglio ringraziare tutti: l’associazione, il console , l’ Unità di crisi , il ministro Tajani e il suo portavoce Vincenzo Nigro. Non ci hanno mai lasciato soli”. Gli italiani ancora a Dubai Intanto, a Dubai , c’è chi deve ancora decidere se restare o partire. Federico Gavazzi, 25 anni, arrivato per uno stage , racconta gli allarmi sui cellulari , l’invito a restare in casa, i boati nella notte . \"Sabato ero fuori con colleghi quando abbiamo visto i primi video degli attacchi . All'inizio sembrava una cosa lontana\". Poi l' allerta del governo emiratino : messaggio sui cellulari, invito a restare in casa e lontano dalle finestre. \"Non mi era mai successo. Il telefono ha suonato con un allarme vero . Ho capito che la situazione era seria\", spiega Federico, sottolineando che “la città funziona, i sistemi di intercettazione sono molto efficienti, ma per la prima volta sto valutando l’idea di rientrare ”. Anche per chi è rimasto, il punto di riferimento resta ancora una volta la rete consolare italiana , che continua a monitorare la situazione e a fornire indicazioni operative . Una lezione concreta di diplomazia Per i ragazzi del progetto “ Ambasciatori del Futuro ”, l’esperienza si è trasformata in una lezione reale : la diplomazia non è solo simulazione, ma gestione concreta delle crisi , tutela dei cittadini , coordinamento internazionale . E in questa crisi , il ruolo della Farnesina e della rete diplomatica italiana è stato centrale : presenza sul territorio , contatto diretto con i connazionali , pianificazione del rientro , comunicazione costante con le famiglie. In giorni di paura e incertezza , la differenza – ripetono organizzatori e genitori – l’ha fatta proprio quella presenza istituzionale che, anche a migliaia di chilometri di distanza, non è mai venuta meno."
    },
    {
        "testata": "AGI",
        "lingua_originale": "it",
        "titolo_orig": "Iran: nei raid Usa morto il leader del team che voleva uccidere Trump",
        "testo_it": "Raid Usa in Iran: ucciso il leader del commando anti-Trump.",
        "priorita": "Altissima",
        "id_gruppo": 6,
        "link": "https://www.agi.it/estero/news/2026-03-04/iran-hegseth-stiamo-vincendo-35939545/",
        "orario": "17:57",
        "timestamp": 1772643461.0,
        "contenuto_esteso": "AGI - L'Iran non ha più nulla: né una leadership , né l' aeronautica , né la marina . E sono passati solo quattro giorni dall'inizio dell' operazione israelo-americana contro il Paese. La vittoria è devastante ma è solo l'inizio. Entro la settimana Stati Uniti e Israele avranno il pieno controllo sui cieli dell'Iran . Ma non finisce qui. Gli Stati Uniti sono pronti ad andare avanti per tutto il tempo necessario, senza alcun limite. È il quadro che traccia il segretario americano alla Guerra , Pete Hegseth , in una conferenza stampa al Pentagono, accompagnato dal capo di Stato maggiore congiunto, Dan Caine, per fornire un aggiornamento sull'operazione 'Epic Fury'. \"L'America sta vincendo in modo decisivo, devastante e senza pietà \", ha dichiarato Hegseth, sottolineando però che la campagna è ancora all'inizio: \"Siamo solo al quarto giorno, le metriche cambiano e altre forze stanno arrivando. È molto presto e, come ha detto il presidente Trump, ci prenderemo tutto il tempo necessario per assicurarci di avere successo\". Il capo del Pentagono ha affermato che la combinazione della potenza aerea statunitense e delle forze israeliane porterà in pochi giorni al controllo completo dei cieli iraniani : \"Le due forze aeree più potenti del mondo avranno il controllo totale dello spazio aereo iraniano . Un controllo totale e incontestato. Voleremo giorno e notte sopra l'Iran, sopra Teheran, colpendo missili, infrastrutture e leadership militare \". Secondo Hegseth, l'obiettivo è \"cacciare, smantellare, demoralizzare, distruggere e sconfiggere le capacità militari iraniane \", mentre Teheran non sarebbe più in grado di sostenere a lungo il confronto: \"L'Iran non può resistere più a lungo di noi, stabiliremo noi il ritmo e il tempo di questa guerra\". La leadership militare iraniana e la marina neutralizzata Il capo del Pentagono ha sostenuto che la leadership militare iraniana è stata in gran parte eliminata o costretta a nascondersi: \"I leader senior sono morti, dispersi o nascosti nei bunker, troppo spaventati per stare nella stessa stanza\", ha affermato. Ovviamente questo ha compromesso la capacità di comando e coordinamento delle forze iraniane. La Marina iraniana \"è stata praticamente neutralizzata\" e che la principale nave da guerra del Paese è stata affondata durante le operazioni, mentre un sottomarino statunitense ha colpito e affondato una nave iraniana nell'Oceano Indiano, al largo dello Sri Lanka, con un siluro Mark-48 , \"il primo affondamento di una nave nemica da parte di un sottomarino americano dalla Seconda guerra mondiale\". La nave era soprannominata Soleimani , come il generale dei Pasdaran ucciso nel 2020 a Baghdad in un raid ordinato da Trump. \"È come se l'avesse colpito due volte\", ha commentato Hegseth. \"La loro Marina non è più un fattore in gioco. Distrutta, decimata, scegliete voi l'aggettivo\", ha detto il capo del Pentagono, secondo cui gli Stati Uniti controllano ormai gran parte delle acque in cui operavano le forze iraniane . Hegseth: \"Ucciso il leader del team che voleva assassinare Trump\" Hegseth ha affermato che nei raid \"è stato ucciso il leader del team iraniano che voleva assassinare il presidente Trump\". \"Sappiamo da tempo che l'Iran aveva intenzione di cercare di uccidere il presidente Trump e gli altri funzionari statunitensi, e sebbene questo non fosse il fulcro dell'impegno, in realtà non è mai stato sollevato dal Presidente o da nessun altro, ho assicurato, e altri hanno assicurato, che i responsabili di ciò sarebbero stati infine inclusi nella lista degli obiettivi. L'inizio dello sforzo era incentrato su missili e lanciatori, e quello è il fulcro. Ma in definitiva, se avessimo avuto l'opportunità di colpire coloro che stanno cercando di colpire specificamente gli americani, lo avremmo fatto. E così alla fine abbiamo avuto l'opportunità\", ha spiegato. Obiettivi e progressi dell'operazione Entrando nel dettaglio della campagna, sono tre gli obiettivi principali : eliminare i sistemi di missili balistici iraniani , distruggere la capacità navale della Repubblica islamica e impedire che Teheran possa ricostruire rapidamente la propria potenza militare . Secondo il Pentagono, i lanci di missili balistici iraniani sono già diminuiti dell'86% rispetto ai primi giorni del conflitto e l'uso di droni d'attacco è calato del 73%, mentre le forze statunitensi hanno ottenuto una superiorità aerea localizzata lungo la costa meridionale iraniana e stanno preparando attacchi sempre più profondi nel territorio del Paese. \"La leva non sta scendendo, sta salendo\", ha affermato Caine, spiegando che le operazioni passeranno da attacchi a distanza con missili a bombardamenti diretti sopra il territorio iraniano con munizioni guidate di precisione . Indagini e implicazioni internazionali Il Pentagono, nel frattempo, indaga sul raid che ha distrutto la scuola femminile nel Sud del Paese. \"Non prendiamo mai di mira obiettivi civili \", ha assicurato Hegseth. Così come esclude che l'intervento della Nato per intercettare un missile balistico iraniano in Turchia possa innescare l' Articolo 5 ."
    },
    {
        "testata": "Adnkronos",
        "lingua_originale": "it",
        "titolo_orig": "Caso Cucchi, Cassazione assolve il colonnello Lorenzo Sabatino",
        "testo_it": "Caso Cucchi: la Cassazione assolve il colonnello Lorenzo Sabatino.",
        "priorita": "Bassa",
        "id_gruppo": 7,
        "link": "https://www.adnkronos.com/cronaca/caso-stefano-cucchi-cassazione-colonnello-lorenzo-sabatino_1aqvZ4VIIK5E1teCBkA2hi",
        "orario": "19:20",
        "timestamp": 1772648418.0,
        "contenuto_esteso": "(Adnkronos) - Rigettati i ricorsi degli altri carabinieri che erano stati condannati o per i quali era stata dichiarata la prescrizione nel processo d'Appello"
    },
    {
        "testata": "Adnkronos",
        "lingua_originale": "it",
        "titolo_orig": "Referendum giustizia, il Sì torna in vantaggio con il 51,5%",
        "testo_it": "Referendum giustizia: il Sì sale al 51,5% nei sondaggi Noto.",
        "priorita": "Bassa",
        "id_gruppo": 8,
        "link": "https://www.adnkronos.com/politica/referendum-giustizia-sondaggio-voto-22-23-marzo_2msuCCU06RFJcWofrHwWKQ",
        "orario": "19:08",
        "timestamp": 1772647722.0,
        "contenuto_esteso": "(Adnkronos) - I dati a meno di tre settimane dal voto rilevati dall'Istituto Noto per Porta a Porta"
    },
    {
        "testata": "BBC News",
        "lingua_originale": "en",
        "titolo_orig": "Iran postpones Khamenei funeral as US-Israeli bombardment continues",
        "testo_it": "Iran: rinviati i funerali di Khamenei per il perdurare dei raid.",
        "priorita": "Altissima",
        "id_gruppo": 6,
        "link": "https://www.bbc.com/news/articles/clygglq6v9go?at_medium=RSS&at_campaign=rss",
        "orario": "18:10",
        "timestamp": 1772644250.0,
        "contenuto_esteso": "An official says more preparations are needed for the three-day ceremony in Tehran, where the supreme leader will lie in state."
    },
    {
        "testata": "BBC News",
        "lingua_originale": "en",
        "titolo_orig": "Spain's Pedro Sánchez hits back at Trump threat to sever trade saying 'no to war'",
        "testo_it": "Sánchez replica a Trump: no alla guerra commerciale con la Spagna.",
        "priorita": "Media",
        "id_gruppo": 10,
        "link": "https://www.bbc.com/news/articles/c93wwq1n542o?at_medium=RSS&at_campaign=rss",
        "orario": "12:30",
        "timestamp": 1772623850.0,
        "contenuto_esteso": "Spain's prime minister delivers a strong rebuttal to US President Donald Trump's threat to end trade with his country."
    },
    {
        "testata": "BBC News",
        "lingua_originale": "en",
        "titolo_orig": "Higher tariffs likely this week, says US Treasury",
        "testo_it": "Tesoro Usa: dazi globali al 15% in arrivo entro la settimana.",
        "priorita": "Alta",
        "id_gruppo": 11,
        "link": "https://www.bbc.com/news/articles/cjwzzq70qgvo?at_medium=RSS&at_campaign=rss",
        "orario": "16:22",
        "timestamp": 1772637742.0,
        "contenuto_esteso": "Scott Bessent says that \"likely sometime this week\" the US will increase its global tariff on imports from the existing 10%."
    },
    {
        "testata": "Deutsche Welle",
        "lingua_originale": "en",
        "titolo_orig": "Greek court upholds convictions of leaders of neo-Nazi party",
        "testo_it": "Grecia: confermata in appello la condanna per i leader di Alba Dorata.",
        "priorita": "Bassa",
        "id_gruppo": 12,
        "link": "https://www.dw.com/en/greek-court-upholds-convictions-of-leaders-of-neo-nazi-party/a-76218570?maca=en-rss-en-world-4025-rdf",
        "orario": "17:57",
        "timestamp": 1772643420.0,
        "contenuto_esteso": "The leaders of the far-right Golden Dawn party were convicted in Greece of having led a criminal organization in a landmark ruling in 2020. An appeals court upheld that decision."
    },
    {
        "testata": "Deutsche Welle",
        "lingua_originale": "en",
        "titolo_orig": "Kenya braces as Middle East conflict escalates",
        "testo_it": "Kenya teme shock economici per l'escalation in Medio Oriente.",
        "priorita": "Media",
        "id_gruppo": 13,
        "link": "https://www.dw.com/en/kenya-braces-as-middle-east-conflict-escalates/a-76218179?maca=en-rss-en-world-4025-rdf",
        "orario": "16:34",
        "timestamp": 1772638440.0,
        "contenuto_esteso": "As tensions rise across the Middle East, Kenyans fear economic shocks, disrupted exports and risks to the more than 400,000 Kenyans working in Gulf states."
    },
    {
        "testata": "Deutsche Welle",
        "lingua_originale": "en",
        "titolo_orig": "India woos global tech, bets big on AI data centers",
        "testo_it": "L'India punta sull'IA, ma i data center pongono sfide energetiche.",
        "priorita": "Bassa",
        "id_gruppo": 14,
        "link": "https://www.dw.com/en/india-woos-global-tech-bets-big-on-ai-data-centers/a-76218185?maca=en-rss-en-world-4025-rdf",
        "orario": "16:34",
        "timestamp": 1772638440.0,
        "contenuto_esteso": "The country is aiming to become a global hub for artificial intelligence and cloud computing infrastructure. But AI data centers' enormous energy and water demands present a challenge."
    },
    {
        "testata": "France 24",
        "lingua_originale": "en",
        "titolo_orig": "US submarine torpedoed Iranian warship in Indian Ocean, Pentagon says",
        "testo_it": "Pentagono: sottomarino Usa ha affondato una nave da guerra iraniana.",
        "priorita": "Altissima",
        "id_gruppo": 6,
        "link": "https://www.france24.com/en/us-submarine-torpedoed-iranian-warship-in-indian-ocean-pentagon-says",
        "orario": "19:23",
        "timestamp": 1772648588.0,
        "contenuto_esteso": "A US submarine sank an Iranian warship in the Indian Ocean, Defense Secretary Pete Hegseth said Wednesday, touting the strike as evidence of America's global reach in its war on Iran. \"An American submarine sunk an Iranian warship that thought it was safe in international waters. Instead, it was sunk by a torpedo,\" Hegseth told a news conference. FRANCE 24's James Vasina reports."
    },
    {
        "testata": "France 24",
        "lingua_originale": "en",
        "titolo_orig": "Macron says he urged Netanyahu to 'refrain from ground offensive' in Lebanon",
        "testo_it": "Macron a Netanyahu: evitare l'offensiva di terra in Libano.",
        "priorita": "Alta",
        "id_gruppo": 15,
        "link": "https://www.france24.com/en/middle-east/20260304-live-deadly-strikes-in-lebanon-iran-claims-complete-control-of-strait-of-hormuz",
        "orario": "19:21",
        "timestamp": 1772648507.0,
        "contenuto_esteso": ""
    },
    {
        "testata": "The New York Times",
        "lingua_originale": "en",
        "titolo_orig": "Live Updates: No Letup in Strikes on Iran, U.S. Says, as Mideast Crisis Widens",
        "testo_it": "Crisi Iran: intensificati i raid, la Turchia abbatte un missile.",
        "priorita": "Altissima",
        "id_gruppo": 3,
        "link": "https://www.nytimes.com/live/2026/03/04/world/iran-war-israel-lebanon-trump",
        "orario": "19:19",
        "timestamp": 1772648390.0,
        "contenuto_esteso": "American officials said the bombing campaign against Iran was accelerating. European countries deployed assets to the region to protect their interests, and Turkey said NATO shot down an Iranian missile heading toward its airspace."
    },
    {
        "testata": "The New York Times",
        "lingua_originale": "en",
        "titolo_orig": "Global Leaders Brace for the Fallout From a Fast Metastasizing War",
        "testo_it": "Leader mondiali in allerta per l'espansione del conflitto in Iran.",
        "priorita": "Altissima",
        "id_gruppo": 6,
        "link": "https://www.nytimes.com/2026/03/04/world/europe/iran-trump-world-reaction.html",
        "orario": "11:37",
        "timestamp": 1772620642.0,
        "contenuto_esteso": "A woman cries after seeing the rubble from a building that was hit by airstrikes in Tehran on Tuesday."
    },
    {
        "testata": "The New York Times",
        "lingua_originale": "en",
        "titolo_orig": "What to Know About Nepal's Gen Z Election",
        "testo_it": "Nepal: al via la campagna elettorale per la Generazione Z.",
        "priorita": "Bassa",
        "id_gruppo": 20,
        "link": "https://www.nytimes.com/2026/03/04/world/asia/nepal-election-gen-z-what-to-know.html",
        "orario": "10:38",
        "timestamp": 1772617098.0,
        "contenuto_esteso": "People attending a campaign rally in Kathmandu, Nepal, on Saturday."
    },
    {
        "testata": "The Guardian",
        "lingua_originale": "en",
        "titolo_orig": "South Sudan risks return to full-blown civil war as violence escalates",
        "testo_it": "Sud Sudan: violenze in aumento, rischio guerra civile totale.",
        "priorita": "Media",
        "id_gruppo": 21,
        "link": "https://www.theguardian.com/world/2026/mar/03/south-sudan-risks-return-civil-war-violence-escalates",
        "orario": "15:49 - 3 Marzo",
        "timestamp": 1772549376.0,
        "contenuto_esteso": "At least 169 killed in raid near Sudan border as clashes between government and opposition forces intensify South Sudan is reeling from an escalating conflict between the government-aligned army and opposition forces and allied groups that observers say risks returning the country to a full-blown civil war. Violent confrontations in the world’s youngest country between the military, which is loyal to President Salva Kiir, and insurgents believed to be allied to the suspended vice-president, Riek Machar, have increased in recent weeks. Continue reading..."
    },
    {
        "testata": "The Guardian",
        "lingua_originale": "en",
        "titolo_orig": "‘Imperialist undertones’: global south condemns US-Israeli war with Iran",
        "testo_it": "Il Sud globale condanna l'intervento Usa-Israele in Iran.",
        "priorita": "Alta",
        "id_gruppo": 6,
        "link": "https://www.theguardian.com/world/2026/mar/03/global-south-condemns-us-israeli-war-with-iran",
        "orario": "13:11 - 3 Marzo",
        "timestamp": 1772539877.0,
        "contenuto_esteso": "China calls it unacceptable to ‘kill leader of sovereign state’, while South Africa questions ‘pre-emptive’ justification Middle East crisis – live updates The US-Israeli war on Iran has been condemned as illegal across much of the global south, with China saying it was unacceptable to “blatantly kill the leader of a sovereign state”. Many countries objected that negotiations between the US and Iran over its nuclear programme and missile capability were not given a chance to succeed before Washington and Israel began bombing, and analysts often saw the war in terms of a colonial-style exercise of might. Continue reading..."
    },
    {
        "testata": "The Guardian",
        "lingua_originale": "en",
        "titolo_orig": "Ghana says at least 55 of its people killed after Russia ‘lured’ them to fight Ukraine",
        "testo_it": "Ghana: 55 cittadini uccisi in Ucraina dopo il reclutamento russo.",
        "priorita": "Media",
        "id_gruppo": 22,
        "link": "https://www.theguardian.com/world/2026/feb/27/ghana-men-killed-fight-russia-ukraine",
        "orario": "16:42 - 27 Febbraio",
        "timestamp": 1772206959.0,
        "contenuto_esteso": "Foreign minister says 272 Ghanaians are thought to have been drawn into battle since 2022, after he visited Kyiv At least 55 Ghanaians have been killed in Russia’s war with Ukraine after being “lured into battle”, Ghana’s foreign minister has said after a visit to Kyiv in which officials raised the issue of Russian recruitment of African people. Reports of African men being attracted to Russia by promises of jobs and ending up on Ukraine’s frontlines have become more frequent in recent months, creating tensions between Moscow and some of the countries involved. Continue reading..."
    },
    {
        "testata": "Le Monde",
        "lingua_originale": "fr",
        "titolo_orig": "EN DIRECT, guerre en Iran : Emmanuel Macron affirme avoir demandé à Benyamin Nétanyahou « de s’abstenir d’une offensive terrestre » au Liban",
        "testo_it": "Macron: chiesto a Netanyahu di non invadere il Libano.",
        "priorita": "Alta",
        "id_gruppo": 15,
        "link": "https://www.lemonde.fr/international/live/2026/03/04/en-direct-guerre-en-iran-emmanuel-macron-affirme-avoir-demande-a-benyamin-netanyahou-de-s-abstenir-d-une-offensive-terrestre-au-liban_6668663_3210.html",
        "orario": "19:18",
        "timestamp": 1772648336.0,
        "contenuto_esteso": "Emmanuel Macron lors de son discours à la base opérationnelle de l’Ile Longue, le 2 mars 2026."
    },
    {
        "testata": "Le Monde",
        "lingua_originale": "fr",
        "titolo_orig": "La relation spéciale du Royaume-Uni avec les Etats-Unis à l’épreuve de Donald Trump",
        "testo_it": "Trump mette alla prova la relazione speciale tra Usa e Regno Unito.",
        "priorita": "Media",
        "id_gruppo": 23,
        "link": "https://www.lemonde.fr/international/article/2026/03/04/la-relation-speciale-du-royaume-uni-avec-les-etats-unis-a-l-epreuve-de-donald-trump_6669559_3210.html",
        "orario": "18:05",
        "timestamp": 1772643905.0,
        "contenuto_esteso": "Le président américain, Donald Trump, et le premier ministre britannique, Keir Starmer, à Aylesbury (Royaume-Uni), le 18 septembre 2025."
    },
    {
        "testata": "Le Monde",
        "lingua_originale": "fr",
        "titolo_orig": "Guerre en Iran : « L’incapacité de la Constitution américaine à limiter le pouvoir de guerre du président met en péril l’ordre mondial »",
        "testo_it": "Analisi: il potere bellico di Trump minaccia l'ordine mondiale.",
        "priorita": "Alta",
        "id_gruppo": 6,
        "link": "https://www.lemonde.fr/idees/article/2026/03/04/guerre-en-iran-l-incapacite-de-la-constitution-americaine-a-limiter-le-pouvoir-de-guerre-du-president-met-en-peril-l-ordre-mondial_6669562_3232.html",
        "orario": "18:56",
        "timestamp": 1772647014.0,
        "contenuto_esteso": "Aux Etats-Unis, l’exécutif et la Cour Suprême ont affaibli la capacité du Congrès à contrôler l’usage de la force militaire américaine, rendant impossible de garantir que le pouvoir agisse dans le respect du droit américain et international, pointent les juristes Kamel El Hilali et Aziz Huq, dans une tribune au « Monde »."
    },
    {
        "testata": "Libération",
        "lingua_originale": "fr",
        "titolo_orig": "Guerre au Moyen-Orient : avec la fermeture du trafic aérien, les arnaques et «l’opportunisme de crise» explosent",
        "testo_it": "Crisi Iran: boom di truffe e speculazioni dopo il blocco dei voli.",
        "priorita": "Bassa",
        "id_gruppo": 5,
        "link": "https://www.liberation.fr/international/moyen-orient/guerre-au-moyen-orient-avec-la-fermeture-du-trafic-aerien-les-arnaques-et-lopportunisme-de-crise-explosent-20260304_JROGLNQYWBFILFWFOT4D4YIXII/",
        "orario": "17:26",
        "timestamp": 1772641587.0,
        "contenuto_esteso": "Les avions bloqués à l'aéroport de Dubaï, le 2 mars 2026."
    },
    {
        "testata": "Libération",
        "lingua_originale": "fr",
        "titolo_orig": "EN DIRECT - Guerre au Moyen-Orient : Macron dit s’être entretenu avec Nétanyahou et les dirigeants libanais",
        "testo_it": "Macron: colloqui in corso con Netanyahu e i leader libanesi.",
        "priorita": "Alta",
        "id_gruppo": 15,
        "link": "https://www.liberation.fr/international/moyen-orient/guerre-au-moyen-orient-les-premiers-rapatries-francais-ont-atterri-a-paris-israel-20260304_GNERINNNDJFBJEOI2DAEFOLBY4/",
        "orario": "19:28",
        "timestamp": 1772648924.0,
        "contenuto_esteso": "Le président français à l'Elysée, le 1er mars 2026."
    },
    {
        "testata": "Libération",
        "lingua_originale": "fr",
        "titolo_orig": "Vu d’Iran : «Le fait d’être ensemble aide les gens à supporter l’atmosphère»",
        "testo_it": "Iran: folla abbatte un monumento dedicato a Khomeini.",
        "priorita": "Alta",
        "id_gruppo": 6,
        "link": "https://www.liberation.fr/international/moyen-orient/vu-diran-le-fait-detre-ensemble-aide-les-gens-a-supporter-latmosphere-20260304_VTV3QOB4QRAQ7EIWDTRL7CLDAI/",
        "orario": "12:54",
        "timestamp": 1772625246.0,
        "contenuto_esteso": "A Galleh Dar, dans le sud-ouest de l'Iran, une foule renverse un monument dédié au fondateur de la république islamique, l'ayatollah Ruhollah Khomeiny, probablement le 28 février 2026."
    },
    {
        "testata": "Al Jazeera",
        "lingua_originale": "en",
        "titolo_orig": "UK police arrest three men on suspicion of spying for China",
        "testo_it": "Regno Unito: tre arresti per spionaggio a favore della Cina.",
        "priorita": "Media",
        "id_gruppo": 24,
        "link": "https://www.aljazeera.com/news/2026/3/4/british-police-arrest-three-men-on-suspicion-of-spying-for-china?traffic_source=rss",
        "orario": "18:57",
        "timestamp": 1772647025.0,
        "contenuto_esteso": "Husband of a lawmaker from Prime Minister Keir Starmer's ruling Labour Party among those arrested, local media report."
    },
    {
        "testata": "Al Jazeera",
        "lingua_originale": "en",
        "titolo_orig": "Trump’s endgame in Iran: Regime change without US ‘boots on the ground’",
        "testo_it": "Analisi: la strategia di Trump per il cambio di regime in Iran.",
        "priorita": "Alta",
        "id_gruppo": 6,
        "link": "https://www.aljazeera.com/news/2026/3/4/trumps-endgame-in-iran-regime-change-without-us-boots-on-the-ground?traffic_source=rss",
        "orario": "18:16",
        "timestamp": 1772644604.0,
        "contenuto_esteso": "Analysts say it would be difficult, if not impossible, to bring down the Iranian system with US-Israeli air power alone."
    },
    {
        "testata": "Al Jazeera",
        "lingua_originale": "en",
        "titolo_orig": "Nearly 66,000 Afghans displaced amid fierce fighting on Pakistan border: UN",
        "testo_it": "Pakistan-Afghanistan: 66mila sfollati per i violenti scontri.",
        "priorita": "Media",
        "id_gruppo": 25,
        "link": "https://www.aljazeera.com/news/2026/3/4/nearly-66000-afghans-displaced-amid-fierce-fighting-on-pakistan-border-un?traffic_source=rss",
        "orario": "17:53",
        "timestamp": 1772643237.0,
        "contenuto_esteso": "UN migration agency warns that escalating violence on Afghanistan-Pakistan border risks further displacement."
    },
    {
        "testata": "South China Morning Post",
        "lingua_originale": "en",
        "titolo_orig": "Google’s Gemini AI chatbot accused of coaching US man to suicide",
        "testo_it": "Google citata in giudizio: il chatbot Gemini avrebbe spinto un uomo al suicidio.",
        "priorita": "Media",
        "id_gruppo": 26,
        "link": "https://www.scmp.com/news/world/united-states-canada/article/3345481/googles-gemini-ai-chatbot-accused-coaching-us-man-suicide?utm_source=rss_feed",
        "orario": "19:16",
        "timestamp": 1772648194.0,
        "contenuto_esteso": "Google is facing a lawsuit from the family of a 36-year-old Florida man who allegedly considered carrying out a “mass casualty attack” and ultimately killed himself under the influence of the company’s Gemini chatbot.\nAccording to a suit filed on Wednesday in federal court in San Jose, California, Jonathan Gavalas began using Gemini for ordinary purposes like help with his writing. But two months of interactions sent him into a dangerous spiral, during which he scoped out a possible violent..."
    },
    {
        "testata": "South China Morning Post",
        "lingua_originale": "en",
        "titolo_orig": "Trump’s 15% global tariffs likely to start this week, US Treasury chief says",
        "testo_it": "Tesoro Usa: dazi globali al 15% attesi entro questa settimana.",
        "priorita": "Alta",
        "id_gruppo": 11,
        "link": "https://www.scmp.com/news/world/united-states-canada/article/3345479/trumps-15-global-tariffs-likely-start-week-us-treasury-chief-says?utm_source=rss_feed",
        "orario": "17:14",
        "timestamp": 1772640841.0,
        "contenuto_esteso": "US Treasury Secretary Scott Bessent said that President Donald Trump’s plan to increase a broad 10 per cent tariff rate to 15 per cent is likely to be implemented this week.\n“That’s likely sometime this week,” Bessent said on Wednesday on CNBC in response to a question about when the increase to 15 per cent would be made.\nBessent’s comments offer the clearest indication yet regarding when the US will follow through on Trump’s pledge to raise tariffs.\nThe president last month imposed a 10 per..."
    },
    {
        "testata": "South China Morning Post",
        "lingua_originale": "en",
        "titolo_orig": "Relief, joy as first flight back from Dubai brings stranded Hongkongers home",
        "testo_it": "Hong Kong: rientrano i primi cittadini bloccati a Dubai.",
        "priorita": "Bassa",
        "id_gruppo": 5,
        "link": "https://www.scmp.com/news/hong-kong/society/article/3345478/relief-joy-first-flight-back-dubai-brings-stranded-hongkongers-home?utm_source=rss_feed",
        "orario": "16:53",
        "timestamp": 1772639610.0,
        "contenuto_esteso": "Hong Kong travellers rejoiced on Wednesday evening after arriving home safely on the first flight from Dubai to the city since US-Israeli strikes on Iran disrupted global air links.\nEmirates flight EK380 was the first to arrive after Dubai’s two airports resumed “limited” operations two days ago, landing at around 9.50pm.\nDubai International Airport and Al Maktoum International Airport were both closed on Saturday after the conflict broke out, with Iran retaliating by targeting US military bases..."
    },
    {
        "testata": "Times of India",
        "lingua_originale": "en",
        "titolo_orig": "'Is it still America or Israel first': Iran's Ali Larijani accuses Trump of dragging US in 'unfair war'",
        "testo_it": "Iran: Larijani accusa Trump di condurre una guerra ingiusta.",
        "priorita": "Alta",
        "id_gruppo": 6,
        "link": "https://timesofindia.indiatimes.com/world/us/is-it-still-america-or-israel-first-irans-ali-larijani-accuses-trump-of-dragging-us-in-unfair-war/articleshow/129045842.cms",
        "orario": "19:21",
        "timestamp": 1772648460.0,
        "contenuto_esteso": "Iran's top security official, Ali Larijani, accused President Trump of initiating an \"unfair war\" and vowed retaliation for the reported killing of Supreme Leader Ayatollah Ali Khamenei. Larijani stated Iran will not negotiate with Washington amid escalating regional conflict, questioning Trump's \"America First\" policy after significant US troop casualties."
    },
    {
        "testata": "Times of India",
        "lingua_originale": "en",
        "titolo_orig": "Attack motivated by Pakistani background: Afghan national assaults neighbour in New York in alleged hate crime",
        "testo_it": "New York: cittadino afghano arrestato per crimine d'odio.",
        "priorita": "Bassa",
        "id_gruppo": 27,
        "link": "https://timesofindia.indiatimes.com/world/us/attack-motivated-by-pakistani-background-afghan-national-assaults-neighbour-in-new-york-in-alleged-hate-crime/articleshow/129044059.cms",
        "orario": "18:52",
        "timestamp": 1772646771.0,
        "contenuto_esteso": ""
    },
    {
        "testata": "Times of India",
        "lingua_originale": "en",
        "titolo_orig": "Dubai under tension? Indian TV star Erica Fernandes shares on-ground reality from UAE emirate amid Iran-US-Israel clashes, sparks debate",
        "testo_it": "Dubai: star indiana documenta la situazione tra le tensioni Iran-Usa.",
        "priorita": "Bassa",
        "id_gruppo": 5,
        "link": "https://timesofindia.indiatimes.com/world/middle-east/dubai-under-tension-indian-tv-star-erica-fernandes-shares-on-ground-reality-from-uae-emirate-amid-iran-us-israel-clashes-sparks-debate/articleshow/129042409.cms",
        "orario": "18:43",
        "timestamp": 1772646238.0,
        "contenuto_esteso": "Indian TV actor Erica J Fernandes shared a Dubai video featuring intercepted aerial threats alongside confident UAE rulers, captioned 'Habibi you're still welcome to Dubai.' Her clarification emphasised her personal experience of safety and efficient handling of regional tensions amid Iran and US-Israel clashes, sparking debate on social media's role in portraying geopolitical realities."
    },
    {
        "testata": "The Hill",
        "lingua_originale": "en",
        "titolo_orig": "Mamdani moves toward universal child care promise",
        "testo_it": "New York: Mamdani e Hochul lanciano il piano per asili nido gratuiti.",
        "priorita": "Bassa",
        "id_gruppo": 28,
        "link": "https://thehill.com/homenews/state-watch/5767348-nyc-free-child-care-program/",
        "orario": "19:10",
        "timestamp": 1772647818.0,
        "contenuto_esteso": "New York City Mayor Zohran Mamdani (D) and New York Gov. Kathy Hochul (D) on Tuesday announced plans to offer 2,000 free child care spots to 2-year-olds, taking the first step toward achieving the mayor’s campaign promise of universal child care. The program will launch this fall, offering free spots to toddlers in four neighborhoods..."
    },
    {
        "testata": "The Hill",
        "lingua_originale": "en",
        "titolo_orig": "House tees up final vote on Department of Homeland Security funding bill",
        "testo_it": "Usa: la Camera avanza sul finanziamento per la sicurezza interna.",
        "priorita": "Media",
        "id_gruppo": 29,
        "link": "https://thehill.com/homenews/house/5767261-house-department-homeland-security-funding/",
        "orario": "19:09",
        "timestamp": 1772647766.0,
        "contenuto_esteso": "The House on Wednesday advanced a GOP-backed Department of Homeland Security (DHS) funding bill, an effort by Republicans to pressure Democrats to end the partial government shutdown in the wake of the U.S. launching strikes against Iran. The panel voted 211-209 to pass the rule, which tees up debate and a vote on the final passage of..."
    },
    {
        "testata": "The Hill",
        "lingua_originale": "en",
        "titolo_orig": "Trump to host roundtable on future of college sports",
        "testo_it": "Trump convoca i vertici dello sport per discutere il futuro del college.",
        "priorita": "Bassa",
        "id_gruppo": 30,
        "link": "https://thehill.com/homenews/administration/5767310-trump-roundtable-college-sports-white-house/",
        "orario": "19:08",
        "timestamp": 1772647704.0,
        "contenuto_esteso": "President Trump will host a number of top executives in the business of college and professional sports for a meeting focused on improving college athletics. The meeting, which was confirmed by The Hill on Wednesday, will take place Friday at The White House and include guests like former Alabama football coach Nick Saban, NCAA president..."
    },
    {
        "testata": "Politico",
        "lingua_originale": "en",
        "titolo_orig": "‘A perfect storm is lining up for Texas Democrats’",
        "testo_it": "Texas: ascesa politica per il democratico James Talarico.",
        "priorita": "Bassa",
        "id_gruppo": 31,
        "link": "https://www.politico.com/news/2026/03/04/talarico-won-his-primary-what-happens-next-is-outside-his-control-00811456",
        "orario": "08:53",
        "timestamp": 1772610798.0,
        "contenuto_esteso": "James Talarico's charmed political journey has broken his way at almost every juncture of his career, from “ The Joe Rogan Experience ” invite as he was weighing a Senate bid last summer to his star turn in Texas’ quorum break to a fundraising windfall over a spiked Stephen Colbert interview in the primary's homestretch. But as he gave his not-quite-victory speech late Tuesday night, Talarico faced a more uncertain future than he had hoped. The Associated Press eventually called the election for him hours later, though voting problems in Rep. Jasmine Crockett's home base of Dallas County delayed the result. And suddenly, it looks like he could face a much tougher opponent than he’d banked on in the general election. Talarico and Democrats had hoped for months that the preacher would get to face scandal-tarred Texas Attorney General Ken Paxton, but Sen. John Cornyn (R-Texas), a less objectionable general-election foil, outperformed expectations and fought him to a draw, forcing a runoff. For the disciplined and studious Democrat who can commit scripture and prepared remarks to memory in a matter of minutes, and who is known by aides to linger over edits to social media posts and ads, the unknown outcome of the runoff is an unwelcome twist, the seemingly rare thing he cannot control. Even with a 12-week head start on whomever voters select as his opponent in a brass-knuckled, dregs-scraping, cash-consuming GOP runoff, Talarico could still face a four-term incumbent with a long track record of big general-election wins. Amid a legal dispute over voting precinct hours in Dallas County, Talarico did not quite declare victory in a short speech just after midnight local time, when he was leading the race but before The Associated Press called it. “We are still waiting for an official call, but we are confident in this movement we've built together,” he said after lamenting what he called “voter suppression.” “We are not just trying to win an election,” Talarico said at his rally in Austin. “We are trying to fundamentally change our politics, and it's working.” Earlier Tuesday, a district judge permitted the Dallas County Democratic Party to extend polling hours until 9 p.m. central, but the Texas Supreme Court granted Attorney General Ken Paxton's request to set aside the votes of those people who were not in line by 7 p.m. The polling problems are just the latest in a long history of voter suppression and voting rights battles in the state — ones that have particularly impacted Black and Hispanic voters. Crockett first gained national attention as a state representative battling against the Texas GOP’s move to pass a law that added new restrictions on voting, an issue once again in the spotlight as her Senate campaign came to a close. In a statement earlier in the evening, Talarico's campaign acknowledged that they were “deeply concerned about the reports of voters being turned away from the polls in Dallas and Williamson counties following the GOP's implementation of precinct-specific voting locations for Election Day.” Crockett initially told supporters Tuesday evening there was \"a lot of confusion today,\" citing Paxton's move and the state Supreme Court's decision. But on Wednesday morning, Crockett said in a statement she spoke with Talarico and conceded the race to him. “This morning I called James and congratulated him on becoming the Senate nominee,” she said. “Texas is primed to turn blue and we must remain united because this is bigger than any one person. This is about the future of all 30 million Texans and getting America back on track.” Talarico ran well in heavily white and Hispanic areas Tuesday, but has conceded he has work to do with Black voters if he’s going to win in November — an effort that could be complicated by the sour final note of voter confusion. The final stretch of the contest pitted Talarico’s and Crockett’s supporters against each other in bitter feuds, often along racial lines, that played out on social media platforms like TikTok and X. Those debates focused on whether Democrats believed Crockett, a Black representative from Dallas, could be elected in a deep-red state — as well as over a claim made by a social media influencer that Talarico had described a former opponent as a “mediocre Black man,” comments he says were misconstrued. Still, his strong performance against Crockett has jolted Democratic hopes of winning Texas for the first time in more than a generation, forging a wider than expected path to flipping the Senate — and out of the wilderness. “I’d be very worried if I were the national Republican Party after tonight,” said Emily Cherniack, the founder and CEO of New Politics, and a longtime Talarico ally. “Strong turnout, especially among Latino voters, signals real dissatisfaction with Republicans in power. That’s a huge warning sign for November for them.” Up until Tuesday, Senate Democrats had staked their chances of flipping the Republican-controlled Senate on just four states: North Carolina, Maine, Ohio and Alaska. But now, some Democrats believe Talarico can cobble together a winning coalition in the most improbable of states — no Democrat has a Senate seat in Texas since 1988 — based on his class-focused message seeking to unite voters across parties. “A perfect storm is lining up for Texas Democrats,” said Mark McKinnon, the former Texas media operative who started out advising Democrat Ann Richards on her gubernatorial campaigns before switching to Republican George W. Bush in 1997. “They have a nominee who can appeal to moderates and soft Republicans. Talarico could be Moses who leads the Lone Star Democrats out of the desert they've been in for 35 years.” Public and private polls have mostly shown close races in either matchup; Talarico would start off with the edge over Paxton but trail Cornyn. “It is still a massive mountain to climb, but this doesn’t hurt the effort,” one former staffer on Kamala Harris’ presidential campaign said of Talarico’s win. Talarico has argued that he can beat either foe. “I think both of them are extraordinarily weak,” Talarico said in an interview with POLITICO just days before Election Day. “Paxton and Cornyn, they're different. Paxton was guilty of illegal corruption. That's why my colleagues and I impeached him in the Texas House. \"But Cornyn is guilty of legalized corruption. He was the deciding vote on the Big, Ugly, Bill which kicked millions of Texas off their health care, took food out of the mouths of hungry Texas kids all to give tax breaks to his donors. Both of them are guilty of using their public offices to enrich their donors — Ken Paxton in an illegal way, but John Cornyn in a legal way. I look forward to prosecuting the case against either of them — whoever makes it out.” Gregory Svirnovskiy contributed to this report."
    },
    {
        "testata": "Politico",
        "lingua_originale": "en",
        "titolo_orig": "Cornyn is still in the fight. Will Trump finally endorse him?",
        "testo_it": "Texas: Cornyn attende l'endorsement di Trump dopo le primarie.",
        "priorita": "Bassa",
        "id_gruppo": 31,
        "link": "https://www.politico.com/news/2026/03/04/cornyn-texas-results-trump-endorsement-00811453",
        "orario": "08:05",
        "timestamp": 1772607935.0,
        "contenuto_esteso": "Sen. John Cornyn defied expectations in the Texas GOP primary on Tuesday. National Republicans believe his unexpectedly strong showing may be enough for President Donald Trump to endorse the embattled incumbent. Trump has privately intimated that he will soon get involved in the Texas Senate race after rebuffing endorsement pleas from both candidates for months, according to a GOP strategist close to the White House who was granted anonymity to speak freely. For months, party leaders worried that Trump would back state Attorney General Ken Paxton, a longtime ally of the president, especially if he dominated in Tuesday’s primary. Then came the results that had Cornyn neck-and-neck with Paxton. With that outcome, the strategist said, it would be “very surprising” if Trump backed Paxton. The stakes are high for Republicans, who fear control of the Senate is hanging in the balance. The GOP hoped to avoid state Rep. James Talarico clinching the Democratic nomination because they see him as able to draw away moderate Republican voters. Republicans “should take him seriously,” said another close Trump administration ally, granted anonymity to be candid. Talarico is a “big reason for Trump to get in for Cornyn and end this thing,” the ally said, especially to free up massive amounts of money that could be spent instead on competitive Senate races in Michigan and Georgia. National Republicans estimated they would have to spend $200 million to protect Cornyn in the runoff. But the GOP strategist shrugged off the price tag. “Look, it will probably cost some money,” the person said. “It's just money, we have a lot of it.” Tuesday’s results were the best-case scenario for establishment Republicans, who worried Cornyn would finish far enough behind Paxton that it would be a slog for him — and a tough sell for a president who hates to back losers. The Texas GOP Senate primary has become a referendum on the future of the Republican Party, testing the strength of the conservative grassroots against the establishment wing. While the MAGA base kept the four-term incumbent — who nearly became Senate majority leader — from getting a majority of the primary vote, the results show the old Republican establishment isn’t quite dead yet. Cornyn’s narrow lead over Paxton was powered by even performances across the state. Even in the most heavily Republican counties where Paxton might have expected to benefit from a MAGA base, the incumbent senator largely held his own: Across more than 110 mostly rural counties that Trump won by at least 50 points in 2024 and were reporting complete results as of early Wednesday morning, Paxton built up only the narrowest of leads, 44 percent to just shy of 40 percent for Cornyn. Meanwhile, Cornyn strengthened his advantage in the more traditional white-collar suburbs, leading by double digits in Travis and Dallas counties as results continued to come in early Wednesday morning. The senator, speaking to reporters on Election Night in Austin, said Republican voters’ choice is “crystal clear.” “I refuse to allow a flawed, self-centered, and shameless candidate like Ken Paxton risk everything we've worked so hard to build over these many years,” he said. “There is simply too much at stake.\" Republicans are well aware that overall control of the Senate may be at risk. Cornyn’s allies warn that scandal-plagued Paxton turns off general election voters, especially if Talarico is their opponent. During Paxton’s decade as attorney general, he faced an impeachment by the GOP-led Texas state House, ethics complaints, a federal securities fraud investigation and a recent divorce complete with allegations of infidelity. Now Paxton is facing another 12 weeks going up against the wrath — and war chest — of the Washington establishment. “John Cornyn spent around $100 million trying to buy this seat,” Paxton told his supporters at a watch party after the race was called. “We spent around $5 million… We prove something they’ll never understand in Washington: Texas is not for sale.” One question is which candidate the voters who backed Rep. Wesley Hunt, who finished a distant third place, will support now — or whether they turn out at all for the May runoff. Lone Star Liberty, a pro-Paxton super PAC, in a memo circulated ahead of Tuesday's election, shrugged off threats that Cornyn would succeed in the runoff by continuing to hammer the attorney general on his litany of scandals, arguing they had nothing new to offer. “Cornyn’s talk of ‘unleashing’ new attacks’ in the runoff is bluster,” the memo states. “The truth is that from day one, his forces fired every bullet they had. There are no new attacks left — only more of the same, at ever-greater cost and with ever-diminishing returns.” Senate Republican operatives – who had entered the night expecting the race to head to a runoff, but unsure of how Cornyn would track against Paxton – were exultant as the incumbent maintained a narrow lead well into the night. A Republican working on Senate campaigns, granted anonymity to speak freely, said Cornyn “proved to be formidable” on Tuesday — bolstering the establishment GOP argument that he is “the most electable” as the party braces for a battle against Talarico. Talarico's lead \"reaffirms the need to have Cornyn as the nominee. Can't risk this to Paxton,\" the GOP operative close to the White House said. Yet some Republicans conceded Cornyn has a tricky path to navigate. He’ll have to square off again with the conservative primary voters who make up Paxton's base. “Runoffs are extremely unpredictable, and head-to-head it could be anyone’s ballgame,\" said Republican strategist Jeff Burton. Dasha Burns, Lisa Kashinsky, Alec Hernandez, Jessica Piper and Erin Doherty contributed reporting"
    },
    {
        "testata": "Politico",
        "lingua_originale": "en",
        "titolo_orig": "Talarico defeats Crockett in Texas Senate Democratic primary",
        "testo_it": "Texas: Talarico vince le primarie democratiche per il Senato.",
        "priorita": "Bassa",
        "id_gruppo": 31,
        "link": "https://www.politico.com/news/2026/03/04/james-talarico-wins-texas-senate-primary-00811090",
        "orario": "07:38",
        "timestamp": 1772606335.0,
        "contenuto_esteso": "State Rep. James Talarico won the Texas Senate Democratic primary, defeating Rep. Jasmine Crockett and giving party leaders the candidate they had quietly seen as the stronger option to flip the ruby-red state. The race was defined by questions of electability and simmering racial tensions , as Talarico and Crockett worked to reassemble the party’s fractured multiracial coalition. That carried over through Tuesday, with both candidates raising concerns that voters had been disenfranchised in Crockett’s home base of Dallas County, which includes a large number of Black voters. The legal dispute over voting precincts in Dallas could cast a shadow over his victory. Crockett told her supporters not to expect a final call on election night. But on Wednesday morning, Crockett said in a statement she spoke with Talarico and conceded the race to him. “This morning I called James and congratulated him on becoming the Senate nominee,” she said. “Texas is primed to turn blue and we must remain united because this is bigger than any one person. This is about the future of all 30 million Texans and getting America back on track.” Talarico, a progressive Seminarian, took a big-tent approach to his campaign by appealing to voters from both parties and independents. He will face off against either Sen. John Cornyn or Texas Attorney General Ken Paxton, who is mounting a right wing challenge to the four-term incumbent. Texas Democrats have failed to win statewide in three decades, but they believe they have a rare opening to flip the Senate seat in November, due to backlash to the Trump administration’s mass deportation efforts and handling of the economy — especially if Paxton emerges from the GOP runoff. There has been scant nonpartisan public polling in the general election, but a recent memo from the National Republican Senatorial Committee shows Cornyn ahead of Talarico by three points, while Talarico would lead Paxton by three points. Gregory Svirnovskiy contributed to this report."
    },
    {
        "testata": "Limes",
        "lingua_originale": "it",
        "titolo_orig": "Trump e Netanyahu sottovalutano l’impero persiano",
        "testo_it": "Limes: Trump e Netanyahu sottovalutano la resilienza iraniana.",
        "priorita": "Alta",
        "id_gruppo": 6,
        "link": "https://www.limesonline.com/rubriche/il-turco-alla-porta/turchia-rimane-punto-riferimento-guerra-usa-iran-israele-scenari-trump-netanyahu-21346455/",
        "orario": "15:03",
        "timestamp": 1772632980.0,
        "contenuto_esteso": "The Donald si è convinto che un successo in Iran potrebbe rilanciarlo in patria. I tre scenari (più uno) della guerra. Re Bibi ha bisogno dello scontro permanente e del Nemico per mantenere gli Usa nella regione. Con l’atteggiamento ambiguo delle petromonarchie Ankara si conferma unica grande potenza dell’area."
    },
    {
        "testata": "Limes",
        "lingua_originale": "it",
        "titolo_orig": "Il Qatar e il Kurdistan iracheno si schierano contro l'Iran e altre notizie interessanti",
        "testo_it": "Geopolitica: Qatar e Kurdistan iracheno contro l'Iran.",
        "priorita": "Media",
        "id_gruppo": 6,
        "link": "https://www.limesonline.com/rubriche/il-mondo-oggi/guerra-iran-mojtaba-khamenei-usa-israele-qatar-spagna-ecuador-sudan-etiopia-21346457/",
        "orario": "11:23",
        "timestamp": 1772619780.0,
        "contenuto_esteso": "La rassegna geopolitica della giornata."
    },
    {
        "testata": "Limes",
        "lingua_originale": "it",
        "titolo_orig": "Perché Hezbollah ha risposto a Israele",
        "testo_it": "Hezbollah si schiera con l'Iran dopo l'uccisione di Khamenei.",
        "priorita": "Alta",
        "id_gruppo": 6,
        "link": "https://www.limesonline.com/dossier/strillone-beirut-rassegna-mediorientale/hezbollah-libano-nella-guerra-in-iran-usa-israele-strategia-sopravvivenza-negoziati-21339315/",
        "orario": "13:40",
        "timestamp": 1772628000.0,
        "contenuto_esteso": "L’uccisione di Khamenei ha spinto il Partito di Dio a schierarsi apertamente con il fronte iraniano. Il conflitto come strumento di sopravvivenza politica in uno Stato debole. Il movimento punta alla resistenza prolungata per sabotare i processi di normalizzazione regionale e possibili accordi del governo con lo Stato ebraico."
    },
    {
        "testata": "Internazionale",
        "lingua_originale": "it",
        "titolo_orig": "La Commissione europea presenta un ambizioso piano industriale",
        "testo_it": "Ue: presentata la strategia industriale per il Made in Europe.",
        "priorita": "Media",
        "id_gruppo": 32,
        "link": "https://www.internazionale.it/ultime-notizie/2026/03/04/commissione-europea-presenta-piano-industriale",
        "orario": "16:12",
        "timestamp": 1772637165.0,
        "contenuto_esteso": "Il 4 marzo la Commissione europea ha presentato, dopo mesi di discussioni tra i ventisette, un piano industriale per valorizzare il “made in Europe”, che punta a rilanciare l’industria continentale e a resistere meglio alla concorrenza cinese Leggi"
    },
    {
        "testata": "Internazionale",
        "lingua_originale": "it",
        "titolo_orig": "Cominciano in Texas le primarie in vista delle elezioni di metà mandato",
        "testo_it": "Texas: al via le primarie per le elezioni di metà mandato.",
        "priorita": "Media",
        "id_gruppo": 31,
        "link": "https://www.internazionale.it/ultime-notizie/2026/03/04/usa-primarie-texas",
        "orario": "14:33",
        "timestamp": 1772631230.0,
        "contenuto_esteso": "Il Texas ha dato il via il 3 marzo alle primarie del Partito repubblicano e del Partito democratico in vista delle elezioni di metà mandato del prossimo novembre, che saranno cruciali per il presidente Donald Trump Leggi"
    },
    {
        "testata": "Internazionale",
        "lingua_originale": "it",
        "titolo_orig": "Nuovi attacchi contro l’Iran, che rivendica il controllo dello stretto di Hormuz",
        "testo_it": "Iran: Teheran rivendica il controllo dello stretto di Hormuz.",
        "priorita": "Alta",
        "id_gruppo": 2,
        "link": "https://www.internazionale.it/ultime-notizie/2026/03/04/iran-rivendica-controllo-stretto-hormuz",
        "orario": "12:28",
        "timestamp": 1772623715.0,
        "contenuto_esteso": "Il 4 marzo Israele e Stati Uniti hanno condotto nuovi attacchi contro l’Iran, Teheran ha rivendicato il “controllo totale” dello stretto di Hormuz e l’esercito israeliano ha intensificato la sua offensiva in Libano Leggi"
    },
    {
        "testata": "Il Manifesto",
        "lingua_originale": "it",
        "titolo_orig": "«Potrebbe arrivare un cattivo peggiore». Ma andiamo avanti",
        "testo_it": "Iran: fosse comuni a Teheran dopo i bombardamenti.",
        "priorita": "Altissima",
        "id_gruppo": 6,
        "link": "https://ilmanifesto.it/potrebbe-arrivare-un-cattivo-peggiore-ma-andiamo-avanti",
        "orario": "23:05 - 3 Marzo",
        "timestamp": 1772575553.0,
        "contenuto_esteso": "A Washington la giornata di dichiarazioni di Donald Trump si apre presto. Nelle stesse ore a Teheran le ruspe scavavano decine di fosse per seppellire le 168 bambine e insegnanti […] The post «Potrebbe arrivare un cattivo peggiore». Ma andiamo avanti first appeared on il manifesto ."
    },
    {
        "testata": "Il Manifesto",
        "lingua_originale": "it",
        "titolo_orig": "Bombardata l’assemblea che sostituiva Khamenei",
        "testo_it": "Iran: bombardata l'assemblea che doveva sostituire Khamenei.",
        "priorita": "Altissima",
        "id_gruppo": 6,
        "link": "https://ilmanifesto.it/bombardata-lassemblea-che-sostituiva-khamenei",
        "orario": "23:05 - 3 Marzo",
        "timestamp": 1772575532.0,
        "contenuto_esteso": "«Siamo in contatto diretto con i governatori. Le circostanze sono particolari, ma il Paese non si è fermato. Sono in corso attività in tutto il Paese», scrive il presidente iraniano […] The post Bombardata l’assemblea che sostituiva Khamenei first appeared on il manifesto ."
    },
    {
        "testata": "Il Sole 24 Ore",
        "lingua_originale": "it",
        "titolo_orig": "Bessent: dazi globali al 15% probabilmente in vigore già questa settimana",
        "testo_it": "Tesoro Usa: dazi globali al 15% operativi da questa settimana.",
        "priorita": "Alta",
        "id_gruppo": 11,
        "link": "https://www.ilsole24ore.com/art/bessent-dazi-globali-15percento-probabilmente-vigore-gia-questa-settimana-AIoz4jlB",
        "orario": "14:59",
        "timestamp": 1772632762.0,
        "contenuto_esteso": "I dazi globali del 15% recentemente annunciati dal presidente Usa Donald Trump entreranno probabilmente in vigore nel corso di questa settimana. Lo ha dichiarato il Segretario al Tesoro Scott Bessent..."
    },
    {
        "testata": "Il Sole 24 Ore",
        "lingua_originale": "it",
        "titolo_orig": "A un passo dall’Ue: la Moldavia occidentale guarda a Bruxelles",
        "testo_it": "Moldavia: le regioni occidentali guardano all'integrazione europea.",
        "priorita": "Bassa",
        "id_gruppo": 34,
        "link": "https://www.ilsole24ore.com/art/a-passo-dall-ue-moldavia-occidentale-guarda-bruxelles-AIKyMSkB",
        "orario": "14:16",
        "timestamp": 1772630168.0,
        "contenuto_esteso": "A pochi chilometri dal confine romeno, nelle regioni occidentali della Moldavia, l’Europa non è un’astrazione geopolitica ma un’esperienza concreta: stipendi più alti, infrastrutture moderne, servizi pubblici più efficienti. Chi vive..."
    },
    {
        "testata": "Il Sole 24 Ore",
        "lingua_originale": "it",
        "titolo_orig": "Ue lancia l’Industrial Accelerator Act, il piano per rafforzare l’industria europea",
        "testo_it": "Ue: lanciato l'Industrial Accelerator Act per l'industria green.",
        "priorita": "Media",
        "id_gruppo": 32,
        "link": "https://www.ilsole24ore.com/art/ue-lancia-l-industrial-accelerator-act-piano-rafforzare-l-industria-europea-AI6PSalB",
        "orario": "12:56",
        "timestamp": 1772625360.0,
        "contenuto_esteso": "Dopo diversi rinvii, la Commissione Europea propone l’Industrial Accelerator Act , una strategia per l’industria che fissa criteri di “ Made in Europe ” e “ basse emissioni di carbonio ” per l’accesso ad appalti..."
    }
];