const newsData = 
[
    {
        "testata": "ANSA",
        "lingua_originale": "it",
        "titolo_orig": "Cuba autorizza per la prima volta imprese miste pubblico-private",
        "testo_it": "Cuba autorizza imprese miste pubblico-private, esclusi sanità, istruzione e difesa.",
        "priorita": "Media",
        "id_gruppo": 1,
        "link": "https://www.ansa.it/sito/notizie/mondo/americalatina/2026/03/04/cuba-autorizza-per-la-prima-volta-imprese-miste-pubblico-private_71502284-0ac3-42fa-9384-54124da877e3.html",
        "orario": "07:30",
        "timestamp": 1772605833.0,
        "contenuto_esteso": "Unica eccezione i settori della sanità, dell'istruzione e della difesa"
    },
    {
        "testata": "ANSA",
        "lingua_originale": "it",
        "titolo_orig": "Messico, la presidente Sheinbaum riceve la Coppa Fifa a 100 giorni dal Mondiale 2026",
        "testo_it": "Messico, presidente Sheinbaum riceve Coppa Fifa a 100 giorni dal Mondiale 2026.",
        "priorita": "Bassa",
        "id_gruppo": 2,
        "link": "https://www.ansa.it/sito/notizie/mondo/americalatina/2026/03/04/messico-la-presidente-sheinbaum-riceve-la-coppa-fifa-a-100-giorni-dal-mondiale_7e80c164-a25e-4abd-8b9c-4595407a10aa.html",
        "orario": "06:52",
        "timestamp": 1772603579.0,
        "contenuto_esteso": "Con Bebeto al Palazzo Nazionale, via al tour del trofeo nel Paese anfitrione"
    },
    {
        "testata": "ANSA",
        "lingua_originale": "it",
        "titolo_orig": "Pasdaran, 'abbiamo il controllo totale dello stretto di Hormuz'",
        "testo_it": "Pasdaran: 'Abbiamo il controllo totale dello stretto di Hormuz'.",
        "priorita": "Alta",
        "id_gruppo": 3,
        "link": "https://www.ansa.it/sito/notizie/mondo/mediooriente/2026/03/04/pasdaran-abbiamo-il-controllo-totale-dello-stretto-di-hormuz_a8c48644-d7bb-4f99-a6e8-9e89b4cd4c0e.html",
        "orario": "05:13",
        "timestamp": 1772597590.0,
        "contenuto_esteso": "Lo afferma l'alto funzionario della Marina della Repubblica Islamica Mohammad Akbarzadeh"
    },
    {
        "testata": "AGI",
        "lingua_originale": "it",
        "titolo_orig": "Medio Oriente in fiamme. Bloccato lo stretto di Hormuz. Il fronte si allarga in Libano",
        "testo_it": "Medio Oriente in fiamme, bloccato Hormuz. Israele attacca Iran e Libano.",
        "priorita": "Alta",
        "id_gruppo": 3,
        "link": "https://www.agi.it/estero/news/2026-03-04/guerra-medio-oriente-libano-35924955/",
        "orario": "06:30",
        "timestamp": 1772602257.0,
        "contenuto_esteso": "AGI - Israele ha lanciato nuovi attacchi contro Iran e Libano. Al quinto giorno di un conflitto che sta riscrivendo gli equilibri geopolitici e mandando in shock i mercati energetici globali, lo scenario si fa sempre più complesso: le Guardie Rivoluzionarie iraniane hanno annunciato il \"controllo totale\" dello Stretto di Hormuz , minacciando di bloccare una delle rotte petrolifere più vitali del pianeta, attraverso la quale transita un quinto del greggio mondiale . La risposta di Washington non si è fatta attendere; il Presidente Donald Trump ha rivendicato la sistematica neutralizzazione della marina e dell’aeronautica di Teheran, assicurando che le unità della Marina USA sono pronte a scortare le petroliere per garantire la continuità dei flussi energetici . Il bilancio delle operazioni militari è imponente. L’esercito statunitense ha confermato di aver colpito quasi 2.000 obiettivi sensibili in territorio iraniano a partire dal raid inaugurale di sabato scorso, che ha portato all'uccisione della Guida Suprema, l’Ayatollah Ali Khamenei . Da allora, Israele ha mantenuto una pressione costante, lanciando ondate di attacchi aerei su vasta scala subito dopo la mezzanotte di mercoledì, in risposta a tre massicci bombardamenti missilistici iraniani diretti verso lo Stato ebraico . La tensione ha travolto anche i paesi limitrofi: l’ Arabia Saudita ha intercettato missili da crociera nei propri cieli, mentre droni d’attacco hanno colpito le vicinanze del consolato americano a Dubai e la base militare di Al-Udeid in Qatar, innescando incendi e costringendo le cancellerie internazionali a una corsa contro il tempo per evacuare i propri cittadini . Il Libano, nuovo fronte di guerra Il Libano è diventato il secondo fronte critico di questa guerra totale . Hezbollah , sostenuto da Teheran , ha intensificato il lancio di razzi e droni contro Israele per vendicare la morte di Khamenei . La reazione delle forze di difesa israeliane è stata immediata e perentoria, con \"avvisi urgenti\" di evacuazione estesi a 16 località nel sud del Paese. Tuttavia, le bombe hanno colpito anche aree precedentemente risparmiate dal conflitto, inclusi edifici residenziali a Baalbek, Aramoun e Saadiyat, oltre a un hotel nel cuore di Beirut . Il ministero della salute libanese ha riportato la morte di decine di civili , tra cui tre paramedici dell'OMS , mentre l’ ONU stima che oltre 30.000 persone siano già state costrette ad abbandonare le proprie case. La strategia di Trump e la disarticolazione iraniana Sul piano politico, Donald Trump , in un incontro alla Casa Bianca con il Cancelliere tedesco Friedrich Merz, ha dipinto un quadro di totale disarticolazione del comando iraniano . Secondo il Presidente americano, due ondate di attacchi congiunti avrebbero eliminato non solo la leadership attuale, ma anche i potenziali successori riuniti per nominare i nuovi vertici. \"La maggior parte delle persone a cui pensavamo è morta\", ha dichiarato Trump, sottolineando che, sebbene il cambio di regime non sia l’obiettivo ufficiale, l’operazione mira a eradicare ogni capacità offensiva di Teheran . L’ammiraglio Brad Cooper ha descritto questa mobilitazione come il più grande dispiegamento di potenza di fuoco statunitense in Medio Oriente da una generazione, superando per intensità persino l'operazione \"shock and awe\" del 2003 contro l'Iraq. Teheran città fantasma e minacce di ritorsione Mentre la Mezzaluna Rossa iraniana parla di almeno 787 vittime sul proprio suolo, Teheran appare oggi come una città fantasma . Nella capitale, un tempo vibrante metropoli da 10 milioni di abitanti, regna un silenzio irreale rotto solo dai controlli dei veicoli blindati agli incroci. Chi è rimasto vive nel terrore , barricato in casa sotto la minaccia costante dei bombardamenti , mentre le testimonianze descrivono quartieri residenziali un tempo trafficati ora deserti. Nonostante la devastazione e la perdita dei propri leader, i vertici superstiti delle Guardie Rivoluzionarie continuano a promettere ritorsioni contro i centri economici dell'intera regione, in un braccio di ferro che rischia di incendiare definitivamente l'intero scacchiere mediorientale ."
    },
    {
        "testata": "AGI",
        "lingua_originale": "it",
        "titolo_orig": "Successione in Iran: Trump frena Pahlavi e parla del cambio di regime",
        "testo_it": "Trump frena Pahlavi su successione in Iran, parla di cambio di regime.",
        "priorita": "Alta",
        "id_gruppo": 4,
        "link": "https://www.agi.it/estero/news/2026-03-04/iran-trump-scarica-palhavi-35920658/",
        "orario": "02:17",
        "timestamp": 1772587020.0,
        "contenuto_esteso": "AGI - Dopo la morte di Ali Khameini , la guida dell'Iran dovrà essere assunta da una figura che abbia sostegno in patria e che quindi non potrà essere Reza Palhavi . Dallo Studio Ovale, il presidente degli Stati Uniti Donald Trump , con accanto il cancelliere tedesco Friedrich Merz, gela le ambizioni del figlio dell'ultimo scià di Persia e offre per la prima volta qualche dettaglio concreto sui suoi piani per il cambio di regime a Teheran . Palhavi, ha spiegato Trump, \"è una brava persona ma mi serve qualcuno che sia popolare in patria , quelli che stiamo attaccando ora sono i fanatici, in Iran i moderati ci sono\". Il presidente americano risponde quindi a chi lo accusava di aver attaccato la Repubblica Islamica senza avere idea di chi avrebbe preso il posto degli ayatollah . Purtroppo i possibili candidati, ha sottolineato, potrebbero essere tutti periti negli attacchi. \"La maggior parte delle persone che avevamo in mente sono morte, Ora abbiamo un altro gruppo. Potrebbero essere morti anche loro, sulla base delle notizie\", ha proseguito il presidente in un apparente riferimento all'attacco che ha colpito l' Assemblea degli Esperti , riunita per scegliere il successore di Khameini . \"Ora che il capobranco è morto, in molti si stanno facendo avanti per chiedere immunità e a un certo punto si smetterà di combattere e vedremo che cosa accadrà\", ha aggiunto Trump, che non si è sbilanciato sulla durata dell' operazione militare ma ha assicurato che \"sta andando benissimo\" e che le capacità militari di Teheran \"sono state distrutte \". \"Non resta più nulla, l' aviazione è andata, la marina è andata, la difesa antiaerea è andata e non hanno più molti missili \", ha affermato il presidente americano che ha poi avuto qualcosa da ridire sul sostegno ricevuto dagli alleati . Se la lì presente Germania \"sta facendo un lavoro fantastico\", la Spagna è \"terribile\" e neanche del Regno Unito c'è da essere contenti. Le tensioni con la Spagna Dopo essere incorsa nelle ire di Washington per essere stata l'unico Paese Nato a rifiutarsi di portare la spesa in difesa al 5% del Pil , la Spagna non ha voluto concedere le basi agli Usa per attaccare l'Iran . \"Non ci servono le loro basi, non hanno nulla che ci serva\", ha tuonato Trump, \" taglieremo tutti i commerci con la Spagna . Non vogliamo avere nulla a che fare con la Spagna\". L'inquilino della Casa Bianca ha assicurato di aver già istruito il segretario al Tesoro, Scott Bessent , perché \" tagli tutti gli affari con Madrid \". \"La Spagna è un membro chiave della NATO , rispetta i suoi impegni e fornisce un contributo significativo alla difesa del territorio europeo \", è la replica di Madrid affidata a fonti della Moncloa. La Spagna, aggiungono le fonti del governo di Pedro Sanchez, è anche una delle principali potenze esportatrici dell'UE e un partner commerciale affidabile per 195 paesi in tutto il mondo, inclusi gli Stati Uniti\". Le difficoltà con il Regno Unito Le cose non sono andate lisce nemmeno con le basi britanniche dato che, ha proseguito Trump, \"abbiamo impiegato tre o quattro giorni per capire dove dovessimo atterrare\". \"Del resto non abbiamo certo a che fare con Winston Churchill \", ha concluso il presidente degli Stati Uniti, che è si è detto \"non contento\" del premier britannico, Keir Starmer , ed è tornato ad attaccarlo per la decisione \"stupida\" e \"scioccante\" di cedere alle Mauritius le isole Chagos , sede di un'importante base militare condivisa con gli Usa . Merz, al suo fianco, ha parlato il meno possibile."
    },
    {
        "testata": "AGI",
        "lingua_originale": "it",
        "titolo_orig": "Dai Pasdaran alla nuova Guida, le tante incognite nell'Iran post Khamenei",
        "testo_it": "Iran post Khamenei: incognite su Guida Suprema, Pasdaran e regime.",
        "priorita": "Alta",
        "id_gruppo": 4,
        "link": "https://www.agi.it/estero/news/2026-03-04/iran-transizione-pasdaran-35918659/",
        "orario": "02:17",
        "timestamp": 1772587020.0,
        "contenuto_esteso": "AGI - La tempistica dell'elezione della nuova Guida Suprema , la resilienza del regime , il consolidamento dei Pasdaran come centro di potere e la fisionomia stessa della Repubblica islamica post-Khamenei sono alcune delle incognite che accompagnano il delicato processo di transizione in atto in Iran , mentre la guerra con Usa e Israele si allarga alla regione. A individuarle e analizzarle, in un'intervista all'AGI, è Nicola Pedde , direttore dell'Institute for Global Studies. Il bombardamento della sede a Qom dell' Assemblea degli Esperti , l'organismo incaricato di votare la nuova Guida Suprema , lascia immaginare che la scelta del nuovo leader della Repubblica islamica \"subirà ritardi \", spiega il direttore del think tank specializzato sui temi della politica, della sicurezza e dell'economia nelle regioni del Medio Oriente e dell'Africa . \"Nominare una nuova Guida durante un conflitto significa farla diventare subito un bersaglio molto preciso e chiaro per Stati Uniti e Israele \", fa notare l'analista. D'altronde, \"la morte di Khamenei non ha comportato, come alcuni pensavano, un crollo immediato del sistema. L'idea dell'Iran come una struttura monolitica al cui comando c'è solo la Guida Suprema è frutto di un'interpretazione errata della Repubblica islamica che ha, invece, un sistema molto reticolare e stratificato di comando \", prosegue Pedde. Dunque \"anche con la morte del leader e delle prime linee di comando delle Forze armate, il sistema è potenzialmente in grado di rigenerare in tempi rapidi queste componenti e di sviluppare una capacità di resilienza maggiore di quanto valutato da parte di Stati Uniti e Israele \". Il ruolo del Consiglio supremo di sicurezza nazionale Un'altra variabile di questa inedita transizione è rappresentata dalla convivenza tra il sistema istituzionale , incarnato dal Consiglio direttivo ad interim - il triumvirato che guida il Paese in attesa dell'elezione della Guida Suprema - e l'organismo che gestisce l'emergenza, vale a dire il Consiglio supremo di sicurezza nazionale , con il suo potente segretario Ali Larijani . \"Il Consiglio supremo\", spiega Pedde, \"è fortemente controllato dai Pasdaran e non è incaricato solo della gestione degli affari militari ma di fatto anche di quelli politici , rappresentando una sorta di camera di compensazione politico-militare \". La consacrazione al potere dei Pasdaran Tra le incognite di questa fase emerge, invece, una chiara certezza, secondo Pedde: la consacrazione al potere dei Guardiani della Rivoluzione ( Irgc ), i Pasdaran appunto. \"Quello cui stiamo assistendo è la definitiva assunzione di potere di questo gruppo che ha posizioni molto diverse rispetto alla componente clericale , è molto meno pragmatico, molto meno orientato al negoziato \". Il passaggio di potere alla seconda generazione Con la morte di Khamenei e di alcune altre figure dell' apparato politico-militare \"è venuto meno l'ultimo baluardo della prima generazione del potere , i rivoluzionari. Ora il potere passa nelle mani della seconda generazione , sostanzialmente dell' Irgc , in una transizione importantissima sotto il profilo interno e con effetti ancora da capire sulla fisionomia del regime \". Riforma costituzionale e ruolo della nuova Guida In questo senso, è possibile che la nomina della nuova Guida possa transitare attraverso una riforma costituzionale o un mutamento del suo ruolo sotto il profilo istituzionale, ipotizza Pedde: \"La seconda generazione non ha interesse a ripristinare un leader politico espressione del clero e non del proprio contesto militare e potrebbe puntare a rafforzare la natura presidenziale delle istituzioni iraniane in modo da poter esercitare un controllo più diretto e soprattutto esprimere figure di vertice \". La forza dell'Irgc e la crisi Bisognerà capire, però, quale tipo di organizzazione l'Irgc riuscirà a darsi in questo contesto di crisi . Quello che è certo, conclude l'analista, \"è che questa operazione militare ha rimosso i vertici politici, soprattutto dello Stato, ma ha lasciato inalterata la catena di comando e di controllo dei Pasdaran \". Se Usa e Israele puntano a una sollevazione popolare in Iran per rovesciare il regime , \"è necessario decapitare la capacità di gestione della repressione e quindi degradare fortemente la forza dell'Irgc , cosa che in questo momento non sta avvenendo e che rappresenta la grande variabile di questa crisi \"."
    },
    {
        "testata": "Adnkronos",
        "lingua_originale": "it",
        "titolo_orig": "Nikkei Average Dives on Fears of Long Middle-East Conflict",
        "testo_it": "Nikkei crolla per timori di lungo conflitto Medio Oriente.",
        "priorita": "Alta",
        "id_gruppo": 3,
        "link": "https://www.adnkronos.com/internazionale/akieng/nikkei-average-dives-on-fears-of-long-middle-east-conflict_27WqaK7suWpe0IFmyY9d3i",
        "orario": "07:39",
        "timestamp": 1772606368.0,
        "contenuto_esteso": "(Adnkronos) - Tokyo, March 4 (Jiji Press)--Japan's benchmark Nikkei 225 stock average sank more than 2,000 points Wednesday as fears of a prolonged conflict between U.S.-Israeli forces and Iran continued to spur risk-adverse selling. The index dropped 2,033.51 points, or 3.61 pct, from Tuesday to end at 54,245.54. It briefly fell below 54,000 for the first time since Feb. 6. The broader TOPIX index finished 138.50 points, or 3.67 pct, lower at 3,633.67. Both indexes ceded ground for the third straight day. The Nikkei's point loss was the fifth largest on record. It gave up about 4,600 points, or 7.82 pct, in the three-day tailspin. Investors are increasingly worried that a prolonged conflict could have a negative impact on the Japanese economy and corporate profits, especially through a blockade of the Strait of Hormuz, a critical chokepoint in a key oil transport route. \"It's unclear how long the increase in crude oil prices (amid the tense Iran situation) will continue, so investors are refraining from buying,\" an official at a major securities firm said. If oil tankers remain unable to pass through the Strait of Hormuz, investor concerns over the economic impact would grow and the Nikkei average could fall to as low as around 45,000, an official at a bank-affiliated brokerage predicted. The Middle East crisis is battering stock markets around the world, with Asian market gauges including South Korea's KOSPI also logging massive drops Wednesday. U.S. stock futures also met with selling in off-hours trading. Meanwhile, an official at another major securities house said that a sense of overheating in the Tokyo market reflecting the Nikkei's recent record-breaking advances has dissipated, adding that individual investors who sold stocks Wednesday may buy them back Thursday and later. \"Conditions are now in place for the market decline to stop,\" the official said. END [Copyright The Jiji Press, Ltd.]"
    },
    {
        "testata": "BBC News",
        "lingua_originale": "en",
        "titolo_orig": "Gas and oil prices soar and shares tumble on fears conflict could escalate",
        "testo_it": "Prezzi gas/petrolio salgono, borse crollano per timori escalation conflitto.",
        "priorita": "Alta",
        "id_gruppo": 3,
        "link": "https://www.bbc.com/news/articles/cr5lz0vgy52o?at_medium=RSS&at_campaign=rss",
        "orario": "21:44 - 3 Marzo",
        "timestamp": 1772570671.0,
        "contenuto_esteso": "Markets react as the conflict in the Middle East intensifies and concerns grow over how long it will last."
    },
    {
        "testata": "BBC News",
        "lingua_originale": "en",
        "titolo_orig": "US and Ecuador forces launch operation to fight drug trafficking",
        "testo_it": "USA e Ecuador combattono narcotraffico e organizzazioni terroristiche.",
        "priorita": "Media",
        "id_gruppo": 7,
        "link": "https://www.bbc.com/news/articles/cgjzz4gn64zo?at_medium=RSS&at_campaign=rss",
        "orario": "04:07",
        "timestamp": 1772593657.0,
        "contenuto_esteso": "Washington says the two countries are combatting what the US calls designated terrorist organisations in the South American country."
    },
    {
        "testata": "BBC News",
        "lingua_originale": "en",
        "titolo_orig": "What to know about the 'two sessions',  China's biggest political meeting",
        "testo_it": "Cina: 'due sessioni', il più grande incontro politico annuale.",
        "priorita": "Media",
        "id_gruppo": 8,
        "link": "https://www.bbc.com/news/articles/c2lrxyke7kro?at_medium=RSS&at_campaign=rss",
        "orario": "01:04",
        "timestamp": 1772582688.0,
        "contenuto_esteso": "The carefully choreographed annual meetings signal the priorities of the world's second-largest economy."
    },
    {
        "testata": "Deutsche Welle",
        "lingua_originale": "en",
        "titolo_orig": "Iraq, caught in the middle, braces for Iran war impact",
        "testo_it": "Iraq travolto dal conflitto Iran: impatto su governo e violenze.",
        "priorita": "Alta",
        "id_gruppo": 3,
        "link": "https://www.dw.com/en/iraq-caught-in-the-middle-braces-for-iran-war-impact/a-76202543?maca=en-rss-en-world-4025-rdf",
        "orario": "09:00",
        "timestamp": 1772611214.8595479,
        "contenuto_esteso": "Iraq is the only country in the Middle East to be targeted by both sides in the current conflict. There, the war could impact everything from the next government to intercommunal violence and civil servants' salaries."
    },
    {
        "testata": "Deutsche Welle",
        "lingua_originale": "en",
        "titolo_orig": "Cuba charges 6 with terrorism over speedboat shootout",
        "testo_it": "Cuba accusa 6 per terrorismo in sparatoria motovedetta da USA.",
        "priorita": "Media",
        "id_gruppo": 9,
        "link": "https://www.dw.com/en/cuba-charges-6-with-terrorism-over-speedboat-shootout/a-76207233?maca=en-rss-en-world-4025-rdf",
        "orario": "09:00",
        "timestamp": 1772611214.859664,
        "contenuto_esteso": "Cuba said the speedboat carrying weapons came from the United States to sow chaos. However, US Secretary of State Marco Rubio said it was not a US operation."
    },
    {
        "testata": "Deutsche Welle",
        "lingua_originale": "en",
        "titolo_orig": "UK stops issuing student visas for 4 countries",
        "testo_it": "UK blocca visti studenti per Afghanistan, Camerun, Myanmar, Sudan.",
        "priorita": "Media",
        "id_gruppo": 10,
        "link": "https://www.dw.com/en/uk-stops-issuing-student-visas-for-4-countries/a-76206876?maca=en-rss-en-world-4025-rdf",
        "orario": "09:00",
        "timestamp": 1772611214.859746,
        "contenuto_esteso": "The UK Home Office has announced an \"emergency brake\" on study visas for nationals from Afghanistan, Cameroon, Myanmar and Sudan. It said people were using the visas to enter as students and subsequently seek asylum."
    },
    {
        "testata": "France 24",
        "lingua_originale": "en",
        "titolo_orig": "'A war of choice': US Congress opens first Iran war vote amid intensifying debate",
        "testo_it": "USA: Senato vota su decisione Trump di agire contro Iran.",
        "priorita": "Alta",
        "id_gruppo": 3,
        "link": "https://www.france24.com/en/americas/20260304-war-of-choice-us-congress-opens-first-iran-war-vote-amid-intensifying-debate",
        "orario": "07:15",
        "timestamp": 1772604912.0,
        "contenuto_esteso": "The US Senate is expected to vote Wednesday on President Donald Trump’s decision to move toward armed conflict with Iran, a rare congressional test of a fast‑escalating Middle East crisis that has unfolded without a clearly defined US strategy for ending the confrontation."
    },
    {
        "testata": "France 24",
        "lingua_originale": "en",
        "titolo_orig": "🔴 War in the Middle East live: Iran Guards say have 'complete control' of Hormuz Strait",
        "testo_it": "Iran: Guardie Rivoluzionarie 'controllo totale' Stretto di Hormuz.",
        "priorita": "Alta",
        "id_gruppo": 3,
        "link": "https://www.france24.com/en/middle-east/20260304-live-deadly-strikes-in-lebanon-iran-claims-complete-control-of-strait-of-hormuz",
        "orario": "06:11",
        "timestamp": 1772601069.0,
        "contenuto_esteso": ""
    },
    {
        "testata": "France 24",
        "lingua_originale": "en",
        "titolo_orig": "War in Middle East live: French fighter jets ‘neutralised’ drones targeting UAE, FM Barrot says",
        "testo_it": "Francia neutralizza droni iraniani diretti verso Emirati Arabi.",
        "priorita": "Alta",
        "id_gruppo": 3,
        "link": "https://www.france24.com/en/middle-east/20260304-live-deadly-strikes-in-lebanon-iran-claims-complete-control-of-strait-of-hormuz",
        "orario": "05:17",
        "timestamp": 1772597834.0,
        "contenuto_esteso": "French Foreign Minister Jean-Noël Barrot on Wednesday said French rafale fighter jets had neutralised Iranian drones targeting the United Arab Emirates. Iran’s Revolutionary Guards claimed “total control” of the Strait of Hormuz as Israel warned it would assassinate any successor to late Ayatollah Ali Khamenei. Follow our liveblog for the latest updates."
    },
    {
        "testata": "The New York Times",
        "lingua_originale": "en",
        "titolo_orig": "Iran Live Updates: Israel Begins ‘Broad Wave of Strikes’ on Iran’s Infrastructure",
        "testo_it": "Iran: Israele inizia 'ondata di attacchi' su infrastrutture.",
        "priorita": "Alta",
        "id_gruppo": 3,
        "link": "https://www.nytimes.com/live/2026/03/03/world/iran-war-israel-lebanon-trump",
        "orario": "06:12",
        "timestamp": 1772601166.0,
        "contenuto_esteso": "The U.S. announced the names of four soldiers who were killed by an Iranian drone on Sunday. The leader of the U.S. Central Command said more than 50,000 troops, 200 fighters, two aircraft carriers and bombers were participating in the fighting."
    },
    {
        "testata": "The New York Times",
        "lingua_originale": "en",
        "titolo_orig": "Israel Seizes Chance to Crush Hezbollah and Remake Mideast Amid Iran War",
        "testo_it": "Israele coglie occasione per schiacciare Hezbollah e rifare Medio Oriente.",
        "priorita": "Alta",
        "id_gruppo": 3,
        "link": "https://www.nytimes.com/2026/03/03/world/middleeast/israel-iran-hezbollah.html",
        "orario": "03:46",
        "timestamp": 1772592393.0,
        "contenuto_esteso": "A worker breaking down structural steel after American airstrikes on Tehran on Monday."
    },
    {
        "testata": "The New York Times",
        "lingua_originale": "en",
        "titolo_orig": "U.S. Hunts for Militants as the Nigerian Military Is Accused of Inaction",
        "testo_it": "USA cerca militanti in Nigeria, accuse di inazione all'esercito.",
        "priorita": "Media",
        "id_gruppo": 14,
        "link": "https://www.nytimes.com/2026/03/03/world/africa/nigeria-security-forces-us-intervention.html",
        "orario": "03:41",
        "timestamp": 1772592070.0,
        "contenuto_esteso": "Razed homes are seen days after an attack that left dozens dead in the Muslim-majority village of Woro, Nigeria, last month."
    },
    {
        "testata": "The Guardian",
        "lingua_originale": "en",
        "titolo_orig": "South Sudan risks return to full-blown civil war as violence escalates",
        "testo_it": "Sud Sudan rischia guerra civile, violenza si intensifica.",
        "priorita": "Media",
        "id_gruppo": 15,
        "link": "https://www.theguardian.com/world/2026/mar/03/south-sudan-risks-return-civil-war-violence-escalates",
        "orario": "15:49 - 3 Marzo",
        "timestamp": 1772549376.0,
        "contenuto_esteso": "At least 169 killed in raid near Sudan border as clashes between government and opposition forces intensify South Sudan is reeling from an escalating conflict between the government-aligned army and opposition forces and allied groups that observers say risks returning the country to a full-blown civil war. Violent confrontations in the world’s youngest country between the military, which is loyal to President Salva Kiir, and insurgents believed to be allied to the suspended vice-president, Riek Machar, have increased in recent weeks. Continue reading..."
    },
    {
        "testata": "The Guardian",
        "lingua_originale": "en",
        "titolo_orig": "‘Imperialist undertones’: global south condemns US-Israeli war with Iran",
        "testo_it": "Sud Globale condanna guerra USA-Israele con Iran: 'Tono imperialista'.",
        "priorita": "Alta",
        "id_gruppo": 3,
        "link": "https://www.theguardian.com/world/2026/mar/03/global-south-condemns-us-israeli-war-with-iran",
        "orario": "13:11 - 3 Marzo",
        "timestamp": 1772539877.0,
        "contenuto_esteso": "China calls it unacceptable to ‘kill leader of sovereign state’, while South Africa questions ‘pre-emptive’ justification Middle East crisis – live updates The US-Israeli war on Iran has been condemned as illegal across much of the global south, with China saying it was unacceptable to “blatantly kill the leader of a sovereign state”. Many countries objected that negotiations between the US and Iran over its nuclear programme and missile capability were not given a chance to succeed before Washington and Israel began bombing, and analysts often saw the war in terms of a colonial-style exercise of might. Continue reading..."
    },
    {
        "testata": "The Guardian",
        "lingua_originale": "en",
        "titolo_orig": "Ghana says at least 55 of its people killed after Russia ‘lured’ them to fight Ukraine",
        "testo_it": "Ghana: 55 cittadini uccisi dopo essere stati 'attratti' da Russia per combattere.",
        "priorita": "Media",
        "id_gruppo": 16,
        "link": "https://www.theguardian.com/world/2026/feb/27/ghana-men-killed-fight-russia-ukraine",
        "orario": "16:42 - 27 Febbraio",
        "timestamp": 1772206959.0,
        "contenuto_esteso": "Foreign minister says 272 Ghanaians are thought to have been drawn into battle since 2022, after he visited Kyiv At least 55 Ghanaians have been killed in Russia’s war with Ukraine after being “lured into battle”, Ghana’s foreign minister has said after a visit to Kyiv in which officials raised the issue of Russian recruitment of African people. Reports of African men being attracted to Russia by promises of jobs and ending up on Ukraine’s frontlines have become more frequent in recent months, creating tensions between Moscow and some of the countries involved. Continue reading..."
    },
    {
        "testata": "Le Monde",
        "lingua_originale": "fr",
        "titolo_orig": "EN DIRECT, Iran : Israël annonce avoir « achevé une nouvelle vague de frappes » en Iran ; Téhéran affirme avoir visé des cibles israéliennes et américaines",
        "testo_it": "Iran: Israele annuncia 'nuova ondata di attacchi'. Teheran risponde.",
        "priorita": "Alta",
        "id_gruppo": 3,
        "link": "https://www.lemonde.fr/international/live/2026/03/04/en-direct-iran-les-premiers-francais-rapatries-du-moyen-orient-ont-atterri-a-paris-israel-annonce-avoir-lance-une-nouvelle-large-vague-de-frappes-sur-l-iran_6668663_3210.html",
        "orario": "05:18",
        "timestamp": 1772597938.0,
        "contenuto_esteso": "Un bombardement israélo-américain sur Téhéran, le 3 mars 2026."
    },
    {
        "testata": "Le Monde",
        "lingua_originale": "fr",
        "titolo_orig": "Confrontés aux attaques de drones, les voisins de l’Iran découvrent leur vulnérabilité",
        "testo_it": "Vicinanza Iran: vulnerabilità a attacchi droni.",
        "priorita": "Alta",
        "id_gruppo": 3,
        "link": "https://www.lemonde.fr/international/article/2026/03/04/confrontes-aux-attaques-de-drones-les-voisins-de-l-iran-decouvrent-leur-vulnerabilite_6669454_3210.html",
        "orario": "05:00",
        "timestamp": 1772596820.0,
        "contenuto_esteso": "Des débris de drones et de missiles iraniens, à Abou Dhabi, le 3 mars 2026."
    },
    {
        "testata": "Le Monde",
        "lingua_originale": "fr",
        "titolo_orig": "Guerre en Iran : Wall Street avance dans le brouillard",
        "testo_it": "Guerra Iran: Wall Street avanza nel 'brouillard'.",
        "priorita": "Alta",
        "id_gruppo": 3,
        "link": "https://www.lemonde.fr/economie/article/2026/03/04/guerre-en-iran-wall-street-avance-dans-le-brouillard_6669465_3234.html",
        "orario": "07:30",
        "timestamp": 1772605855.0,
        "contenuto_esteso": "Des traders à Wall Street, New York, le 2 mars 2026."
    },
    {
        "testata": "Libération",
        "lingua_originale": "fr",
        "titolo_orig": "Guerre au Moyen-Orient : des funérailles nationales pour Khamenei mercredi, Israël prévient que son successeur sera une «cible» à éliminer",
        "testo_it": "Iran: funerali nazionali per Khamenei, Israele: successore sarà 'bersaglio'.",
        "priorita": "Alta",
        "id_gruppo": 4,
        "link": "https://www.liberation.fr/international/moyen-orient/guerre-au-moyen-orient-les-premiers-rapatries-francais-ont-atterri-a-paris-israel-20260304_GNERINNNDJFBJEOI2DAEFOLBY4/",
        "orario": "07:53",
        "timestamp": 1772607226.0,
        "contenuto_esteso": "Vue d'ensemble du complexe de l'ayatollah Ali Khamenei à Téhéran, en Iran, le 22 février 2026, avant les frappes aériennes."
    },
    {
        "testata": "Libération",
        "lingua_originale": "fr",
        "titolo_orig": "Golfe en guerre : le détroit d’Ormuz au cœur d’un choc énergétique mondial",
        "testo_it": "Golfo in guerra: Stretto di Hormuz al centro di shock energetico globale.",
        "priorita": "Alta",
        "id_gruppo": 3,
        "link": "https://www.liberation.fr/international/golfe-en-guerre-le-detroit-dormuz-au-coeur-dun-choc-energetique-mondial-20260303_WXLNBSRGAZB2LPDZVQR4CPKNOA/",
        "orario": "19:51 - 3 Marzo",
        "timestamp": 1772563909.0,
        "contenuto_esteso": "Des tankers dans le détroit d'Ormuz, au large de Fujaïrah (Emirats arabes unis), le 3 mars 2026."
    },
    {
        "testata": "Libération",
        "lingua_originale": "fr",
        "titolo_orig": "Guerre au Moyen-Orient : l’administration Trump limite la casse économique",
        "testo_it": "Guerra Medio Oriente: amministrazione Trump limita danni economici.",
        "priorita": "Alta",
        "id_gruppo": 3,
        "link": "https://www.liberation.fr/international/amerique/guerre-au-moyen-orient-ladministration-trump-limite-la-casse-economique-20260303_YOV6WHPA3ZEUPG6GLYLFNHBA5Y/",
        "orario": "20:52 - 3 Marzo",
        "timestamp": 1772567520.0,
        "contenuto_esteso": "Donald Trump recevant le chancelier allemand à la Maison Blanche, le 3 mars."
    },
    {
        "testata": "Al Jazeera",
        "lingua_originale": "en",
        "titolo_orig": "China set to release new five-year plan at National People’s Congress",
        "testo_it": "Cina: nuovo piano quinquennale al Congresso Nazionale del Popolo.",
        "priorita": "Media",
        "id_gruppo": 8,
        "link": "https://www.aljazeera.com/news/2026/3/4/china-set-to-release-new-five-year-plan-at-national-peoples-congress?traffic_source=rss",
        "orario": "07:31",
        "timestamp": 1772605904.0,
        "contenuto_esteso": "Beijing is expected to set a growth target of 4.5 to 5 percent cent for 2026 at this week's NPC."
    },
    {
        "testata": "Al Jazeera",
        "lingua_originale": "en",
        "titolo_orig": "Video: Smoke seen rising after explosion near Baghdad airport",
        "testo_it": "Iraq: fumo visto dopo esplosione vicino aeroporto Baghdad.",
        "priorita": "Alta",
        "id_gruppo": 3,
        "link": "https://www.aljazeera.com/video/newsfeed/2026/3/4/video-smoke-seen-rising-after-explosion-near-baghdad-airport?traffic_source=rss",
        "orario": "07:16",
        "timestamp": 1772604989.0,
        "contenuto_esteso": "Video shared by Iraqi media shows the moment of an explosion near Baghdad International Airport in Iraq's capital."
    },
    {
        "testata": "South China Morning Post",
        "lingua_originale": "en",
        "titolo_orig": "North Korea’s hostage strategy packs more bite in post-Iran US shake-up",
        "testo_it": "Corea Nord: strategia ostaggi più efficace dopo scossa USA-Iran.",
        "priorita": "Media",
        "id_gruppo": 18,
        "link": "https://www.scmp.com/week-asia/politics/article/3345386/north-koreas-hostage-strategy-packs-more-bite-post-iran-us-shake?utm_source=rss_feed",
        "orario": "07:39",
        "timestamp": 1772606372.0,
        "contenuto_esteso": "For decades, North Korea’s most potent insurance policy has been the threat it poses to Seoul, guaranteeing that any US move against Kim Jong-un’s regime would first exact an unbearable toll on the South.\nNow, a new Pentagon blueprint may have just offered that survival strategy Washington’s seal of approval.\nThe new National Defence Strategy, presented to a Senate Armed Services Committee hearing on Tuesday, calls on Seoul to take “primary” responsibility for deterring North Korea, with..."
    },
    {
        "testata": "South China Morning Post",
        "lingua_originale": "en",
        "titolo_orig": "Low-cost models surpass Tesla in China; Geely makes bets amid price wars: 7 EV reads",
        "testo_it": "Veicoli elettrici: modelli low-cost superano Tesla in Cina.",
        "priorita": "Media",
        "id_gruppo": 19,
        "link": "https://www.scmp.com/business/china-evs/article/3345201/low-cost-models-surpass-tesla-china-geely-makes-bets-amid-price-wars-7-ev-reads?utm_source=rss_feed",
        "orario": "07:30",
        "timestamp": 1772605808.0,
        "contenuto_esteso": "We have put together stories from our coverage on electric and new energy vehicles from the past two weeks to help you stay informed. If you would like to see more of our reporting, please consider subscribing.\n1. Low-cost models dominate China EV sales, surpassing Tesla and BYD\nAmid intensifying competition among Chinese electric-vehicle (EV) makers last year, relatively inexpensive models from Geely Auto and Wuling Motor Holdings topped the sales chart, surpassing cars from BYD and Tesla.\n2...."
    },
    {
        "testata": "South China Morning Post",
        "lingua_originale": "en",
        "titolo_orig": "Philippines’ Duterte-Carpio ordered to answer impeachment charges over wealth, threats",
        "testo_it": "Filippine: Duterte-Carpio deve rispondere accuse impeachment per ricchezza.",
        "priorita": "Media",
        "id_gruppo": 20,
        "link": "https://www.scmp.com/news/asia/southeast-asia/article/3345384/philippines-duterte-carpio-ordered-answer-impeachment-charges-over-wealth-threats?utm_source=rss_feed",
        "orario": "07:26",
        "timestamp": 1772605598.0,
        "contenuto_esteso": "Philippine lawmakers ordered Vice-President Sara Duterte-Carpio on Wednesday to respond to impeachment complaints against her after finding substance to allegations involving unexplained wealth, the misuse of public funds and making public threats against President Ferdinand Marcos Jnr.\nThe daughter of former president Rodrigo Duterte is seen as a front runner for the 2028 presidential election, and has said she will run for the top post.\nShe survived a similar impeachment bid last year, which..."
    },
    {
        "testata": "Times of India",
        "lingua_originale": "en",
        "titolo_orig": "UAE residents return home on 3 exceptional Etihad Rail trains from Saudi border",
        "testo_it": "UAE: residenti tornano a casa su treni Etihad Rail dal confine saudita.",
        "priorita": "Bassa",
        "id_gruppo": 21,
        "link": "https://timesofindia.indiatimes.com/world/middle-east/uae-residents-return-home-on-3-exceptional-etihad-rail-trains-from-saudi-border/articleshow/129010676.cms",
        "orario": "06:48",
        "timestamp": 1772603320.0,
        "contenuto_esteso": "Etihad Rail, typically a freight operator, deployed three exceptional passenger services to safely transport UAE citizens and residents from the Saudi border to Abu Dhabi. This emergency mission, coordinated with Abu Dhabi authorities, demonstrated the railway's readiness as a critical pillar of national emergency response infrastructure during regional travel disruptions."
    },
    {
        "testata": "Times of India",
        "lingua_originale": "en",
        "titolo_orig": "Dubai Airport issues warning over fabricated, digitally altered videos circulating online",
        "testo_it": "Dubai Airport avverte su video falsi e alterati digitalmente.",
        "priorita": "Bassa",
        "id_gruppo": 22,
        "link": "https://timesofindia.indiatimes.com/world/middle-east/dubai-airport-issues-warning-over-fabricated-digitally-altered-videos-circulating-online/articleshow/129008912.cms",
        "orario": "06:03",
        "timestamp": 1772600618.0,
        "contenuto_esteso": "Dubai International Airport has issued a warning regarding digitally manipulated videos falsely depicting incidents at the airport. Authorities urge the public to rely on official updates and refrain from sharing unverified content, emphasizing potential legal consequences under UAE regulations for spreading misinformation."
    },
    {
        "testata": "Times of India",
        "lingua_originale": "en",
        "titolo_orig": "'We've just begun': US says it has bombed over 2,000 targets in Iran - top developments",
        "testo_it": "USA: 'Abbiamo appena iniziato', bombardato oltre 2000 target in Iran.",
        "priorita": "Alta",
        "id_gruppo": 3,
        "link": "https://timesofindia.indiatimes.com/world/middle-east/weve-just-begun-us-says-it-has-bombed-over-2000-targets-in-iran-top-developments/articleshow/129001839.cms",
        "orario": "02:34",
        "timestamp": 1772588096.0,
        "contenuto_esteso": "Israel and the United States have launched a major joint operation against Iran.  The campaign involves extensive strikes targeting Iranian military and nuclear facilities.  Iran has retaliated, hitting US diplomatic sites and energy infrastructure across the region.  The conflict has spread, causing casualties and displacement.  Global energy prices are rising as the Strait of Hormuz remains a point of tension."
    },
    {
        "testata": "The Hill",
        "lingua_originale": "en",
        "titolo_orig": "Cornyn, Paxton in ugly runoff: 5 takeaways from Texas, North Carolina primaries",
        "testo_it": "Primarie Texas/North Carolina: Cornyn, Paxton in testa.",
        "priorita": "Bassa",
        "id_gruppo": 23,
        "link": "https://thehill.com/homenews/campaign/5766310-texas-north-carolina-primary-elections-takeaways/",
        "orario": "06:25",
        "timestamp": 1772601956.0,
        "contenuto_esteso": "Texas Republicans are bracing for an ugly Senate runoff, while Democrats wait to see the outcome of its contest for the upper chamber, with primary season in full swing. Voters in Texas, North Carolina and Arkansas headed to the polls Tuesday to kick start the 2026 midterm cycle. Texas held competitive primaries for Senate, state attorney general and a..."
    },
    {
        "testata": "The Hill",
        "lingua_originale": "en",
        "titolo_orig": "Gonzales forced into House GOP runoff amid affair allegations",
        "testo_it": "Texas: Gonzales va al ballottaggio per la Camera dopo accuse.",
        "priorita": "Bassa",
        "id_gruppo": 23,
        "link": "https://thehill.com/homenews/house/5763494-gonzales-herrera-runoff-texas/",
        "orario": "05:22",
        "timestamp": 1772598153.0,
        "contenuto_esteso": "Rep. Tony Gonzales (R-Texas) and gun rights YouTuber Brandon Herrera are projected head into a runoff after allegations of an affair with a former staffer rocked the lawmaker's candidacy, according to Decision Desk HQ.  Gonzales and Herrera will head into a May runoff in the GOP contest for the state’s 23rd Congressional District. Military veteran Keith..."
    },
    {
        "testata": "The Hill",
        "lingua_originale": "en",
        "titolo_orig": "Crenshaw ousted by Toth in Texas GOP primary upset",
        "testo_it": "Texas GOP: Crenshaw sconfitto da Toth in primarie.",
        "priorita": "Bassa",
        "id_gruppo": 23,
        "link": "https://thehill.com/homenews/house/5763470-toth-defeats-crenshaw-texas-house-primary/",
        "orario": "05:13",
        "timestamp": 1772597623.0,
        "contenuto_esteso": "Texas State Rep. Steve Toth (R) is projected to pull off a victory in Tuesday’s primary, unseating fourth-term incumbent Rep. Dan Crenshaw (R-Texas), according to Decision Desk HQ. Toth’s win all but ensures he will represent the deep-red Texas 2nd Congressional District in Congress next year. Crenshaw, who has at times broken with President Trump,..."
    },
    {
        "testata": "Politico",
        "lingua_originale": "en",
        "titolo_orig": "Talarico defeats Crockett in Texas Senate Democratic primary",
        "testo_it": "Texas: Talarico sconfigge Crockett primarie Senato Democratico.",
        "priorita": "Bassa",
        "id_gruppo": 23,
        "link": "https://www.politico.com/news/2026/03/04/james-talarico-wins-texas-senate-primary-00811090",
        "orario": "07:38",
        "timestamp": 1772606335.0,
        "contenuto_esteso": "State Rep. James Talarico won the Texas Senate Democratic primary, defeating Rep. Jasmine Crockett and giving party leaders the candidate they had quietly seen as the stronger option to flip the ruby-red state. The race was defined by questions of electability and simmering racial tensions , as Talarico and Crockett worked to reassemble the party’s fractured multiracial coalition. That carried over through Tuesday, with both candidates raising concerns that voters had been disenfranchised in Crockett’s home base of Dallas County, which includes a large number of Black voters. The legal dispute over voting precincts in Dallas could cast a shadow over his victory. Crockett told her supporters not to expect a final call on election night. Talarico, a progressive Seminarian, took a big-tent approach to his campaign by appealing to voters from both parties and independents. He will face off against either Sen. John Cornyn or Texas Attorney General Ken Paxton, who is mounting a right wing challenge to the four-term incumbent. Texas Democrats have failed to win statewide in three decades, but they believe they have a rare opening to flip the Senate seat in November, due to backlash to the Trump administration’s mass deportation efforts and handling of the economy — especially if Paxton emerges from the GOP runoff. There has been scant nonpartisan public polling in the general election, but a recent memo from the National Republican Senatorial Committee shows Cornyn ahead of Talarico by three points, while Talarico would lead Paxton by three points."
    },
    {
        "testata": "Politico",
        "lingua_originale": "en",
        "titolo_orig": "Scandal-plagued Rep. Tony Gonzales forced to runoff",
        "testo_it": "Texas: Rep. Tony Gonzales va al ballottaggio per scandalo.",
        "priorita": "Bassa",
        "id_gruppo": 23,
        "link": "https://www.politico.com/news/2026/03/04/tony-gonzales-runoff-texas-gop-primary-00811372",
        "orario": "06:24",
        "timestamp": 1772601876.0,
        "contenuto_esteso": "Scandal-embroiled Rep. Tony Gonzales (R-Texas) on Tuesday was forced into a runoff election after weeks of backlash to reports alleging he had an affair with a former staffer, who later took her own life. He will face Brandon Herrera — a 2nd Amendment influencer who goes by “TheAKGuy” on social media — in late May. That sets them up for yet another expensive and prolonged contest like they experienced in 2024, when Gonzales prevailed by one percentage point . Gonzales, who has represented the west Texas district since 2021, has faced calls to resign from several of his GOP colleagues after new evidence emerged of his alleged affair. Gonzales previously denied the affair and repeatedly said he would not step down. Gonzales’ South Texas district favors Republicans, but could potentially become competitive should Hispanic voters sour on the GOP this cycle or stay home. Even with the scandal, House GOP leadership declined to rescind their endorsements of Gonzales and were content to wait and see how the voters decided. “There’s a primary there in less than a week, these things will play out,” Speaker Mike Johnson said recently ."
    },
    {
        "testata": "Politico",
        "lingua_originale": "en",
        "titolo_orig": "Rep. Dan Crenshaw ousted by primary challenger to his right",
        "testo_it": "Texas: Rep. Dan Crenshaw sconfitto da sfidante di destra.",
        "priorita": "Bassa",
        "id_gruppo": 23,
        "link": "https://www.politico.com/news/2026/03/04/dan-crenshaw-loses-texas-primary-challenge-00810922",
        "orario": "06:01",
        "timestamp": 1772600498.0,
        "contenuto_esteso": "Rep. Dan Crenshaw (R-Texas) was ousted by a primary challenger who successfully cast the four-term incumbent as anti-Trump and capitalized on a redrawn district. State Rep. Steve Toth — who had the backing of Sen. Ted Cruz (R-Texas) — beat Crenshaw on Tuesday night, all but assuring his seat in Congress given the district’s safe-red bend. Crenshaw was the only incumbent GOP representative in Texas without President Donald Trump’s support and had at times split with the president, including in his criticism of Trump’s refusal to accept his 2020 election loss. And Toth, with Cruz’s help, focused his campaign on casting Crenshaw as insufficiently conservative for the district, which was redrawn in the GOP’s recent Texas redistricting push. “You deserve an unwavering fighter, a Republican who walks the walk,” Cruz said in a recent ad for Toth ."
    },
    {
        "testata": "Limes",
        "lingua_originale": "it",
        "titolo_orig": "Hezbollah trascina il Libano in una nuova guerra",
        "testo_it": "Libano trascinato in guerra da Hezbollah dopo morte Khamenei.",
        "priorita": "Alta",
        "id_gruppo": 4,
        "link": "https://www.limesonline.com/dossier/strillone-beirut-rassegna-mediorientale/hezbollah-libano-nella-guerra-in-iran-usa-israele-strategia-sopravvivenza-negoziati-21339315/",
        "orario": "15:14 - 3 Marzo",
        "timestamp": 1772547240.0,
        "contenuto_esteso": "L’uccisione di Khamenei ha spinto il Partito di Dio a schierarsi apertamente con il fronte iraniano. Il conflitto come strumento di sopravvivenza politica in uno Stato debole. Il movimento punta alla resistenza prolungata per sabotare i processi di normalizzazione regionale e possibili accordi del governo con Israele."
    },
    {
        "testata": "Limes",
        "lingua_originale": "it",
        "titolo_orig": "Logistica e obiettivi della guerra contro l'Iran",
        "testo_it": "Logistica e obiettivi guerra contro Iran: schieramento USA e arsenale Teheran.",
        "priorita": "Alta",
        "id_gruppo": 3,
        "link": "https://www.limesonline.com/articoli/obiettivi-e-logistica-guerra-preventiva-usa-israele-contro-iran-portaerei-missili-cambio-di-regime-21329896/",
        "orario": "15:49 - 3 Marzo",
        "timestamp": 1772549340.0,
        "contenuto_esteso": "La scelta di Usa e Israele di attaccare congiuntamente è essenziale per conseguire i rispettivi scopi in Medio Oriente. Il costoso schieramento militare americano e l’arsenale missilistico di Teheran. Russia e Cina protestano, ma non possono o non vogliono andare oltre."
    },
    {
        "testata": "Limes",
        "lingua_originale": "it",
        "titolo_orig": "Israele avanza in Libano, la Francia amplia l'arsenale nucleare e altre notizie interessanti",
        "testo_it": "Israele avanza in Libano, Francia amplia arsenale nucleare.",
        "priorita": "Alta",
        "id_gruppo": 3,
        "link": "https://www.limesonline.com/rubriche/il-mondo-oggi/iran-usa-israele-libano-hezbollah-francia-macron-nucleare-openai-anthropic-cina-india-canada-21338735/",
        "orario": "11:56 - 3 Marzo",
        "timestamp": 1772535360.0,
        "contenuto_esteso": "La rassegna geopolitica della giornata."
    },
    {
        "testata": "Internazionale",
        "lingua_originale": "it",
        "titolo_orig": "I motivi del caos in Medio Oriente",
        "testo_it": "Motivi caos Medio Oriente: guerra coinvolge regione, conseguenze disastrose.",
        "priorita": "Alta",
        "id_gruppo": 3,
        "link": "https://www.internazionale.it/opinione/pierre-haski/2026/03/04/i-motivi-del-caos-in-medio-oriente",
        "orario": "07:24",
        "timestamp": 1772605489.0,
        "contenuto_esteso": "Pochi giorni dopo l’inizio delle ostilità tra Israele, Stati Uniti e Iran la guerra ha coinvolto l’intera regione. Con conseguenze disastrose per i civili Leggi"
    },
    {
        "testata": "Internazionale",
        "lingua_originale": "it",
        "titolo_orig": "Oggi è più difficile parlare di pace",
        "testo_it": "Oggi più difficile parlare di pace: smantellati meccanismi opposizione.",
        "priorita": "Media",
        "id_gruppo": 24,
        "link": "https://www.internazionale.it/opinione/william-shoki/2026/03/04/oggi-e-piu-difficile-parlare-di-pace",
        "orario": "06:00",
        "timestamp": 1772600402.0,
        "contenuto_esteso": "Non c’è più un movimento contro la guerra. I meccanismi che un tempo davano forza all’opposizione popolare sono stati sistematicamente smantellati Leggi"
    },
    {
        "testata": "Internazionale",
        "lingua_originale": "it",
        "titolo_orig": "La Corte penale internazionale di fronte ai potenti del mondo",
        "testo_it": "Corte Penale Internazionale affronta pressioni senza precedenti.",
        "priorita": "Media",
        "id_gruppo": 25,
        "link": "https://www.internazionale.it/video/2026/03/04/corte-penale-internazionale",
        "orario": "05:30",
        "timestamp": 1772598602.0,
        "contenuto_esteso": "Dal 2002 la Corte cerca di sfidare l’impunità di importanti leader in carica. Ma oggi si trova ad affrontare pressioni senza precedenti. Il video Leggi"
    },
    {
        "testata": "Il Manifesto",
        "lingua_originale": "it",
        "titolo_orig": "«Potrebbe arrivare un cattivo peggiore». Ma andiamo avanti",
        "testo_it": "USA: Trump, 'potrebbe arrivare un cattivo peggiore'. Iran: fosse comuni.",
        "priorita": "Alta",
        "id_gruppo": 4,
        "link": "https://ilmanifesto.it/potrebbe-arrivare-un-cattivo-peggiore-ma-andiamo-avanti",
        "orario": "23:05 - 3 Marzo",
        "timestamp": 1772575553.0,
        "contenuto_esteso": "A Washington la giornata di dichiarazioni di Donald Trump si apre presto. Nelle stesse ore a Teheran le ruspe scavavano decine di fosse per seppellire le 168 bambine e insegnanti […] The post «Potrebbe arrivare un cattivo peggiore». Ma andiamo avanti first appeared on il manifesto ."
    },
    {
        "testata": "Il Manifesto",
        "lingua_originale": "it",
        "titolo_orig": "Bombardata l’assemblea che sostituiva Khamenei",
        "testo_it": "Iran: bombardata assemblea che sostituiva Khamenei.",
        "priorita": "Alta",
        "id_gruppo": 4,
        "link": "https://ilmanifesto.it/bombardata-lassemblea-che-sostituiva-khamenei",
        "orario": "23:05 - 3 Marzo",
        "timestamp": 1772575532.0,
        "contenuto_esteso": "«Siamo in contatto diretto con i governatori. Le circostanze sono particolari, ma il Paese non si è fermato. Sono in corso attività in tutto il Paese», scrive il presidente iraniano […] The post Bombardata l’assemblea che sostituiva Khamenei first appeared on il manifesto ."
    },
    {
        "testata": "Il Manifesto",
        "lingua_originale": "it",
        "titolo_orig": "Israele avanza in Libano. «Andremo in treno a Beirut»",
        "testo_it": "Israele avanza in Libano: 'Andremo in treno a Beirut'.",
        "priorita": "Alta",
        "id_gruppo": 3,
        "link": "https://ilmanifesto.it/israele-avanza-in-libano-andremo-in-treno-a-beirut",
        "orario": "23:05 - 3 Marzo",
        "timestamp": 1772575531.0,
        "contenuto_esteso": "Abbiamo l’esercito più forte al mondo, ne sono orgoglioso. Arriveremo a Beirut in treno», prevede con ottimismo Ruben Marli, sindaco di Nahariya, a pochi chilometri dal confine con il Libano, […] The post Israele avanza in Libano. «Andremo in treno a Beirut» first appeared on il manifesto ."
    },
    {
        "testata": "Il Sole 24 Ore",
        "lingua_originale": "it",
        "titolo_orig": "Australia, stato di Victoria approva legge sul diritto al lavoro da casa",
        "testo_it": "Australia Victoria approva legge: diritto al lavoro da casa.",
        "priorita": "Bassa",
        "id_gruppo": 26,
        "link": "https://www.ilsole24ore.com/art/australia-stato-victoria-approva-legge-diritto-lavoro-casa-AI1wcHlB",
        "orario": "07:53",
        "timestamp": 1772607180.0,
        "contenuto_esteso": "Lo stato australiano di Victoria è pronto a garantire alle persone il diritto legale di lavorare da casa due giorni alla settimana. La legge entrerà in vigore il 1° settembre,..."
    },
    {
        "testata": "Il Sole 24 Ore",
        "lingua_originale": "it",
        "titolo_orig": "Iran, Pasdaran: controlliamo stretto di Hormuz. Katz: eliminare successore Khamenei",
        "testo_it": "Iran, Pasdaran: controlliamo Hormuz. Katz: eliminare successore Khamenei.",
        "priorita": "Alta",
        "id_gruppo": 3,
        "link": "https://www.ilsole24ore.com/art/iran-pasdaran-controlliamo-stretto-hormuz-teheran-merz-spinge-ue-ad-attaccarci-AIssUFlB",
        "orario": "06:46",
        "timestamp": 1772603160.0,
        "contenuto_esteso": ""
    },
    {
        "testata": "Il Sole 24 Ore",
        "lingua_originale": "it",
        "titolo_orig": "Gaza: la chiusura dei valichi blocca di nuovo gli aiuti umanitari",
        "testo_it": "Gaza: chiusura valichi blocca aiuti umanitari, ospedali a corto carburante.",
        "priorita": "Alta",
        "id_gruppo": 27,
        "link": "https://www.ilsole24ore.com/art/gaza-chiusura-valichi-blocca-nuovo-aiuti-umanitari-AIt14tkB",
        "orario": "06:12",
        "timestamp": 1772601120.0,
        "contenuto_esteso": "Gli ospedali hanno carburante solo per tre giorni. Oggi riapre il valico di Karem Shalon, punto di ingresso principale delle forniture"
    }
];