const newsData = 
[
    {
        "testata": "ANSA",
        "lingua_originale": "it",
        "titolo_orig": "Starmer insiste, Gb resta fuori da guerra diretta all'Iran",
        "testo_it": "Starmer ribadisce: UK fuori dal conflitto diretto con l'Iran; destra critica.",
        "priorita": "Alta",
        "id_gruppo": 1,
        "link": "https://www.ansa.it/sito/notizie/mondo/mediooriente/2026/03/04/starmer-insiste-gb-resta-fuori-da-guerra-diretta-alliran_6b0e4966-821c-4086-a8a1-193217a6d715.html",
        "orario": "12:28",
        "timestamp": 1772623705.0,
        "contenuto_esteso": "L'opposizione di destra lo attacca sulla scia di Trump, 'Teheran ci ha attaccato'"
    },
    {
        "testata": "ANSA",
        "lingua_originale": "it",
        "titolo_orig": "Turchia all'Iran, 'evitare l'espansione del conflitto'",
        "testo_it": "Turchia all'Iran: evitare l'escalation dopo missile intercettato diretto ad Ankara.",
        "priorita": "Alta",
        "id_gruppo": 2,
        "link": "https://www.ansa.it/sito/notizie/mondo/europa/2026/03/04/turchia-alliran-evitare-lespansione-del-conflitto_ecba7239-0bf8-4c02-8a0c-1ec2a4384375.html",
        "orario": "12:26",
        "timestamp": 1772623560.0,
        "contenuto_esteso": "Dopo un missile iraniano diretti verso il Paese e intercettato"
    },
    {
        "testata": "ANSA",
        "lingua_originale": "it",
        "titolo_orig": "Ankara, 'ci difenderemo da ogni attacco'",
        "testo_it": "Ankara: ci difenderemo da ogni attacco dopo intercettazione missili iraniani.",
        "priorita": "Alta",
        "id_gruppo": 2,
        "link": "https://www.ansa.it/sito/notizie/mondo/europa/2026/03/04/ankara-ci-difenderemo-da-ogni-attacco_63127f66-8fe1-41d7-874e-543c789b2e40.html",
        "orario": "12:08",
        "timestamp": 1772622522.0,
        "contenuto_esteso": "Dopo missili iraniani diretti verso la Turchia intercettati"
    },
    {
        "testata": "AGI",
        "lingua_originale": "it",
        "titolo_orig": "Medio Oriente in fiamme. L'Idf avanza in Libano. Katz: \"Qualsiasi nuovo leader iraniano sa...",
        "testo_it": "Medio Oriente in fiamme: Israele attacca Iran/Libano, shock mercati energetici.",
        "priorita": "Alta",
        "id_gruppo": 1,
        "link": "https://www.agi.it/estero/news/2026-03-04/guerra-medio-oriente-libano-35924955/",
        "orario": "12:35",
        "timestamp": 1772624121.0,
        "contenuto_esteso": "AGI - Israele ha lanciato nuovi attacchi contro Iran e Libano. Al quinto giorno di un conflitto che sta riscrivendo gli equilibri geopolitici e mandando in shock i mercati energetici globali, lo scenario si fa sempre più complesso: le Guardie Rivoluzionarie iraniane hanno annunciato il \"controllo totale\" dello Stretto di Hormuz , minacciando di bloccare una delle rotte petrolifere più vitali del pianeta, attraverso la quale transita un quinto del greggio mondiale . La risposta di Washington non si è fatta attendere; il Presidente Donald Trump ha rivendicato la sistematica neutralizzazione della marina e dell’aeronautica di Teheran, assicurando che le unità della Marina USA sono pronte a scortare le petroliere per garantire la continuità dei flussi energetici . Nel frattempo è ancora mistero sulla successione di Ali Khamenei , a cui l'Iran si prepara a dire addio in una lunga cerimonia funebre che doveva iniziare oggi, ma è stata subito rinviata . La tempistica delle esequie della Guida Suprema (Rahbar, in farsi) rimane incerta come anche quella della scelta del suo successore: un annuncio in questo momento significherebbe offrire subito un chiaro bersaglio al nemico. Israeliani e americani coi loro raid stanno esplicitamente ostacolando il processo di selezione. Ieri, a Qom, è stato bombardato l'edificio dove si riunisce l'Assemblea degli esperti, l'organismo responsabile dell'elezione della Guida. Uno dei suoi 88 membri, l'ayatollah Ahmad Khatami, ha assicurato alla tv di Stato che la nomina \"è vicina\". Intantom il Libano è diventato il secondo fronte critico di questa guerra totale . Hezbollah , sostenuto da Teheran , ha intensificato il lancio di razzi e droni contro Israele per vendicare la morte di Khamenei . La reazione delle forze di difesa israeliane è stata immediata e perentoria, con \"avvisi urgenti\" di evacuazione estesi a 16 località nel sud del Paese. Tuttavia, le bombe hanno colpito anche aree precedentemente risparmiate dal conflitto, inclusi edifici residenziali a Baalbek, Aramoun e Saadiyat, oltre a un hotel nel cuore di Beirut . Il ministero della salute libanese ha riportato la morte di decine di civili , tra cui tre paramedici dell'OMS , mentre l’ ONU stima che oltre 30.000 persone siano già state costrette ad abbandonare le proprie case. La diretta della giornata 13.02 Turchia, 'missile abbattuto da difesa Nato nel Mediterraneo' Un missile balistico lanciato dall'Iran e diretto verso lo spazio aereo turco dopo aver attraversato Siria e Iraq e' stato distrutto dalle difese aeree della NATO nel Mediterraneo orientale. Lo ha annunciato il ministero della Difesa turco. Ankara ha dichiarato in una nota che non ci sono state vittime o feriti nell'incidente, aggiungendo che la Turchia si riserva il diritto di rispondere a qualsiasi azione ostile nei suoi confronti, avvertendo al contempo le parti di astenersi da qualsiasi misura che possa aggravare il conflitto 12.53 Media Teheran, bilancio vittime sale a 1045 Il bilancio delle vittime degli attacchi israelo-americani in Iran si aggrava a 1.045. Lo riportano media locali. 12.40 Oggi il Senato Usa voterà risoluzione per bloccare guerra Il Senato degli Stati Uniti voterà oggi una risoluzione bipartisan sui poteri di guerra che limiterebbe la capacita' del presidente Donald Trump di continuare l'azione militare in Iran senza l'approvazione del Congresso, nel contesto del conflitto in rapida escalation iniziato con gli attacchi di Stati Uniti e Israele sulla Repubblica islamica. La risoluzione, co-promossa dal senatore democratico della Virginia Tim Kaine, mira a limitare i poteri bellici del presidente e sara' un banco di prova di lealta' per alcuni esponenti dell'estrema destra del partito repubblicano, che per anni hanno sostenuto la promessa di Trump di tenere l'America fuori da guerre all'estero. 11.52 Rinviati i funerali di Khamenei a Teheran La cerimonia funebre per l'ayatollah Ali' Khamenei prevista oggi a Teheran è stata rinviata. Lo ha annunciato la tv di stato. \"In considerazione dell'affluenza senza precedenti di partecipanti al funerale, la cerimonia di commiato per la salma dell'Imam martire della Ummah e' stata rinviata e la nuova data sarà comunicata a breve\", ha spiegato la giornalista che ha dato la notizia. 11.47 Idf, appello per l'evacuazione a tutti gli abitanti sud Libano L'esercito israeliano ha lanciato un appello, esortando tutti i residenti delle citta' e dei villaggi nel Libano meridionale a spostarsi a nord del fiume Litani. \"Ai residenti del Libano meridionale: dovete dirigervi immediatamente a nord del fiume Litani. Per la vostra sicurezza, dovete evacuare immediatamente le vostre case e spostarvi a nord, oltre il fiume Litani\", ha affermato in un video su X il portavoce in lingua araba dell'Idf, Avichay Adraee. 10.53 Assemblea Esperti, vicini a scegliere nuova Guida Suprema L'Iran \"è vicino\" a scegliere la prossima Guida Suprema. Lo ha annunciato l'ayatollah Ahmad Khatami, un alto esponente religioso iraniano membro sia del potente Consiglio dei Guardiani che dell'Assemblea degli Esperti, l'organismo preposto a eleggere il successore del defunto Ali Khamenei. \"La Guida Suprema sarà identificata al più presto, siamo vicini a una conclusione, tuttavia la situazione nel Paese è di guerra\", ha dichiarato Khatami alla tv di Stato come riporta AL Jazeera. 10.44 Iran, il figlio Khamenei è sopravvissuto agli attacchi Mojtaba Khamene i, figlio della defunta Guida Suprema dell'Iran, è sopravvissuto agli attacchi israelo-americani contro il Paese, secondo due fonti iraniane citate dall'agenzia di stampa Reuters. La notizia arriva dopo che ieri Iran International - testata vicino all'opposizione iraniana della diaspora - aveva annunciato l'elezione di Mojtaba come successero di Ali Khamenei, ucciso nel primo giorno di guerra. La notizia per ora non è stata confermata. Israele questa mattina ha subito avvertito che qualsiasi nuovo leader sarebbe diventat o bersaglio dei suoi attacchi .    Nonostante non sia mai stato eletto o nominato a una carica governativa, un cablogramma diplomatico statunitense del 2008 affermava che Mojtaba era \"ampiamente considerato all'interno del regime come un leader e un manager capace e risoluto, che un giorno potrebbe succedergli almeno in parte alla leadership nazionale\". 10.27 Kuwait, ondata su missili e droni in arrivo sul Paese \"Le forze armate del Kuwait stanno attualmente affrontando un'ondata di missili e droni rilevati nello spazio aereo dello Stato del Kuwait e stanno svolgendo le loro missioni per affrontarli e intercettarli\". Lo ha dichiarato l'esercito in una nota. Un giornalista dell'AFP sul posto ha segnalato il suono delle sirene a Kuwait City. 10.25 Il bilancio del raid Idf in Libano sale a 56 morti e 335 feriti In Libano si aggrava il bilancio degli attacchi israeliani che hanno causato almeno 56 morti e oltre 335 feriti in due giorni. Uno dei raid odierni dell'Idf ha colpito un hotel alla periferia di Beirut, il Comfort Hotel , nel sobborgo di Baabda, al di fuori delle aree solitamente prese di mira dalle forze israeliane. L'attacco ha provocato ingenti danni materiali e ha ferito almeno cinque persone, tra cui un receptionist in gravi condizioni. Nel frattempo, il quartiere di Dahye , un sobborgo della capitale libanese, è stato nuovamente preso di mira questa mattina, mentre l'esercito israeliano continua a emettere ordini di evacuazione per l'area, nonostante migliaia di residenti siano fuggiti nelle ultime 48 ore. Tra le città attaccate ieri sera c'erano Saadiyat e Aramoun, a sud di Beirut , dove il Centro Operativo di Emergenza Libanese ha segnalato sei morti e otto feriti, secondo un comunicato. 09.53 Idf, abbattuto un caccia iraniano L'aviazione israeliana ha abbattuto un aereo dell'aeronautica militare israeliana. Lo ha annunciato l'Idf.    \"Un caccia F-35I (Adir) dell'aeronautica militare israeliana ha abbattuto un caccia YAK-130 dell'aeronautica militare iraniana nei cieli di Teheran\", si legge in un post. \"È la prima volta nella storia che un F-35I abbatte un aereo da combattimento con equipaggio\", si spiega. Una nave militare affonda in Sri Lanka, soccorsi 30 marinai Le autorità dello Sri Lanka hanno riferito di aver tratto in salvo 30 marinai di una nave della marina militare iraniana che sta affondando poco fuori dalle sue acque territoriali. Lo ha dichiarato in parlamento il ministro degli Esteri, Vijitha Herath , precisando che i 30 feriti a bordo della fregata Iris Dena sono stati trasportati in un ospedale di Galle, nel sud dell'isola. L'equipaggio di 180 persone aveva lanciato una richiesta di soccorso all'alba. Il ministro Herath non ha fornito ulteriori dettagli sull'accaduto, ma ha affermato che lo Sri Lanka adotterà tutte le misure appropriate. I media locali hanno riportato che la nave aveva segnalato un'emergenza al largo della costa di Galle, nella parte meridionale dello Sri Lanka. Cina: \"La sicurezza dello Stretto di Hormuz è interesse di tutti\" La sicurezza e la stabilità nello S tretto di Hormuz sono nell'interesse di tutte le parti ed e' essenziale prevenire l'impatto negativo del conflitto nella regione sull'economia globale, ha ammonito la portavoce del ministero degli Esteri cinese Mao Ning in un briefing con la stampa. Sànchez: \"No alla guerra\" \"La posizione del Governo si riassume in tre parole: 'No alla guerra'\". Lo dice il primo ministro, spagnolo, Pedro Sànchez , che sta rilasciando una dichiarazione ufficiale dopo le parole di ieri di Donald Trump . Idf, in corso \"attacchi su vasta scala\" a Teheran L'Aeronautica militare israeliana sta effettuando una \" vasta\" ondata di attacchi contro obiettivi del regime iraniano a Teheran . Lo ha annunciato l'esercito (Idf), dopo che le agenzie iraniane avevano segnalato forti esplosioni nel Nord-Est della capitale. Morte di Khamenei, oggi al via 3 giorni di commemorazioni Inizierà questa sera (alle 19.30 ora italiana) la cerimonia di commemorazione della defunta Guida Suprema dell'Iran, Ali Khamenei . Lo riporta l'agenzia Tasnim specificando che la cerimonia durerà tre giorni. I dettagli per il funerale di Khamenei, che sarà annunciato a breve, sono ancora in fase di definizione, ha aggiunto l'agenzia. Sempre secondo i media ufficiali iraniani, Khamenei, - ucciso dai raid americani e israeliani di sabato su Teheran - sarà sepolto nella città santa di Mashhad. Qui era nato 86 anni fa e qui è sepolto suo padre, nel santuario dell' Imam Reza ."
    },
    {
        "testata": "AGI",
        "lingua_originale": "it",
        "titolo_orig": "L'avvertimento di Danny Danon, ambasciatore israeliano all’Onu",
        "testo_it": "Ambasciatore Israele all'ONU: ultimatum di 24 ore prima degli attacchi in Libano.",
        "priorita": "Alta",
        "id_gruppo": 1,
        "link": "https://www.agi.it/estero/video/2026-03-04/danon-ambasciatore-israele-onu-35930512/",
        "orario": "11:42",
        "timestamp": 1772620948.0,
        "contenuto_esteso": "AGI  - Israele ha cominciato gli attacchi nel sud del Libano e avviato le evacuazioni. Martedì, al Palazzo di Vetro , a New York sede dell’ Onu , era arrivato l’ ultimatum di 24 ore . Israele aveva lanciato l’ avvertimento ai funzionari iraniani che si trovano in Libano a lasciare il Paese. “Ogni rappresentante del regime iraniano che si trova in Libano se ne vada entro 24 ore. Non ci sarà un posto in cui siete al sicuro”, aveva detto Danny Danon , ambasciatore israeliano all’Onu ."
    },
    {
        "testata": "AGI",
        "lingua_originale": "it",
        "titolo_orig": "Successione in Iran: Trump frena Pahlavi e parla del cambio di regime",
        "testo_it": "Trump su successione Iran: frena Pahlavi, serve sostegno interno dopo morte Khamenei.",
        "priorita": "Alta",
        "id_gruppo": 1,
        "link": "https://www.agi.it/estero/news/2026-03-04/iran-trump-scarica-palhavi-35920658/",
        "orario": "02:17",
        "timestamp": 1772587020.0,
        "contenuto_esteso": "AGI - Dopo la morte di Ali Khameini , la guida dell'Iran dovrà essere assunta da una figura che abbia sostegno in patria e che quindi non potrà essere Reza Palhavi . Dallo Studio Ovale, il presidente degli Stati Uniti Donald Trump , con accanto il cancelliere tedesco Friedrich Merz, gela le ambizioni del figlio dell'ultimo scià di Persia e offre per la prima volta qualche dettaglio concreto sui suoi piani per il cambio di regime a Teheran . Palhavi, ha spiegato Trump, \"è una brava persona ma mi serve qualcuno che sia popolare in patria , quelli che stiamo attaccando ora sono i fanatici, in Iran i moderati ci sono\". Il presidente americano risponde quindi a chi lo accusava di aver attaccato la Repubblica Islamica senza avere idea di chi avrebbe preso il posto degli ayatollah . Purtroppo i possibili candidati, ha sottolineato, potrebbero essere tutti periti negli attacchi. \"La maggior parte delle persone che avevamo in mente sono morte, Ora abbiamo un altro gruppo. Potrebbero essere morti anche loro, sulla base delle notizie\", ha proseguito il presidente in un apparente riferimento all'attacco che ha colpito l' Assemblea degli Esperti , riunita per scegliere il successore di Khameini . \"Ora che il capobranco è morto, in molti si stanno facendo avanti per chiedere immunità e a un certo punto si smetterà di combattere e vedremo che cosa accadrà\", ha aggiunto Trump, che non si è sbilanciato sulla durata dell' operazione militare ma ha assicurato che \"sta andando benissimo\" e che le capacità militari di Teheran \"sono state distrutte \". \"Non resta più nulla, l' aviazione è andata, la marina è andata, la difesa antiaerea è andata e non hanno più molti missili \", ha affermato il presidente americano che ha poi avuto qualcosa da ridire sul sostegno ricevuto dagli alleati . Se la lì presente Germania \"sta facendo un lavoro fantastico\", la Spagna è \"terribile\" e neanche del Regno Unito c'è da essere contenti. Le tensioni con la Spagna Dopo essere incorsa nelle ire di Washington per essere stata l'unico Paese Nato a rifiutarsi di portare la spesa in difesa al 5% del Pil , la Spagna non ha voluto concedere le basi agli Usa per attaccare l'Iran . \"Non ci servono le loro basi, non hanno nulla che ci serva\", ha tuonato Trump, \" taglieremo tutti i commerci con la Spagna . Non vogliamo avere nulla a che fare con la Spagna\". L'inquilino della Casa Bianca ha assicurato di aver già istruito il segretario al Tesoro, Scott Bessent , perché \" tagli tutti gli affari con Madrid \". \"La Spagna è un membro chiave della NATO , rispetta i suoi impegni e fornisce un contributo significativo alla difesa del territorio europeo \", è la replica di Madrid affidata a fonti della Moncloa. La Spagna, aggiungono le fonti del governo di Pedro Sanchez, è anche una delle principali potenze esportatrici dell'UE e un partner commerciale affidabile per 195 paesi in tutto il mondo, inclusi gli Stati Uniti\". Le difficoltà con il Regno Unito Le cose non sono andate lisce nemmeno con le basi britanniche dato che, ha proseguito Trump, \"abbiamo impiegato tre o quattro giorni per capire dove dovessimo atterrare\". \"Del resto non abbiamo certo a che fare con Winston Churchill \", ha concluso il presidente degli Stati Uniti, che è si è detto \"non contento\" del premier britannico, Keir Starmer , ed è tornato ad attaccarlo per la decisione \"stupida\" e \"scioccante\" di cedere alle Mauritius le isole Chagos , sede di un'importante base militare condivisa con gli Usa . Merz, al suo fianco, ha parlato il meno possibile."
    },
    {
        "testata": "Adnkronos",
        "lingua_originale": "it",
        "titolo_orig": "Huawei lancia prodotti e soluzioni di rete ottica di nuova generazione per promuovere una nuova crescita nell'era dell'IA",
        "testo_it": "Huawei lancia soluzioni ottiche di nuova generazione per l'era IA al MWC.",
        "priorita": "Bassa",
        "id_gruppo": 3,
        "link": "https://www.adnkronos.com/immediapress/pr-newswire/huawei-lancia-prodotti-e-soluzioni-di-rete-ottica-di-nuova-generazione-per-promuovere-una-nuova-crescita-nellera-dellia_1FyYKSyNGecwQZhaXdX6TS",
        "orario": "12:46",
        "timestamp": 1772624812.0,
        "contenuto_esteso": "(Adnkronos) - BARCELLONA, Spagna, 4 marzo 2026 /PRNewswire/ -- In occasione dell'evento di lancio dei prodotti e delle soluzioni Huawei durante il MWC Barcelona 2026, Bob Chen, Presidente della linea di prodotti ottici Huawei, ha presentato i prodotti e le soluzioni di rete ottica di nuova generazione per promuovere la sinergia tra IA e reti, accelerando l'evoluzione verso una rete completamente ottica, incentrata sull'IA."
    },
    {
        "testata": "Adnkronos",
        "lingua_originale": "it",
        "titolo_orig": "Japan, Canada to Cooperate on Evacuation of Citizens",
        "testo_it": "Giappone e Canada coopereranno per evacuare cittadini in emergenza all'estero.",
        "priorita": "Media",
        "id_gruppo": 4,
        "link": "https://www.adnkronos.com/internazionale/akieng/japan-canada-to-cooperate-on-evacuation-of-citizens_7rFbfVWpZPOZ1lxsf8SPRC",
        "orario": "12:45",
        "timestamp": 1772624701.0,
        "contenuto_esteso": "(Adnkronos) - Tokyo, March 4 (Jiji Press)--Japan and Canada on Wednesday signed a memorandum to work together for the evacuation of their citizens when emergencies occur in other countries. Japanese Foreign Minister Toshimitsu Motegi and Canadian Ambassador to Japan Ian McKay signed the memorandum at a ceremony in Tokyo. The agreement came amid growing tensions over Iran following the U.S.-Israeli strikes on the country and ahead of Canadian Prime Minister Mark Carney's visit to Japan from Friday. This is the third such memorandum for Japan, following ones with South Korea and Australia. Japan and Canada cooperated in the evacuation of citizens during the Sudanese civil war in 2023 and when the security condition deteriorated in Haiti in 2024. END [Copyright The Jiji Press, Ltd.]"
    },
    {
        "testata": "BBC News",
        "lingua_originale": "en",
        "titolo_orig": "Gas and oil prices soar and shares tumble on fears conflict could escalate",
        "testo_it": "Prezzi gas/petrolio in aumento e crollo azioni per timori escalation Medio Oriente.",
        "priorita": "Alta",
        "id_gruppo": 1,
        "link": "https://www.bbc.com/news/articles/cr5lz0vgy52o?at_medium=RSS&at_campaign=rss",
        "orario": "21:44 - 3 Marzo",
        "timestamp": 1772570671.0,
        "contenuto_esteso": "Markets react as the conflict in the Middle East intensifies and concerns grow over how long it will last."
    },
    {
        "testata": "BBC News",
        "lingua_originale": "en",
        "titolo_orig": "Spain's Pedro Sánchez hits back at Trump threat to sever trade saying 'no to war'",
        "testo_it": "Premier spagnolo Sánchez risponde a Trump: \"No alla guerra\" contro minaccia commerciale.",
        "priorita": "Alta",
        "id_gruppo": 6,
        "link": "https://www.bbc.com/news/articles/c93wwq1n542o?at_medium=RSS&at_campaign=rss",
        "orario": "12:30",
        "timestamp": 1772623850.0,
        "contenuto_esteso": "Spain's prime minister delivers a strong rebuttal to US President Donald Trump's threat to end trade with his country."
    },
    {
        "testata": "BBC News",
        "lingua_originale": "en",
        "titolo_orig": "Three men arrested in UK on suspicion of spying for China",
        "testo_it": "Tre uomini arrestati nel Regno Unito con sospetto spionaggio per conto della Cina.",
        "priorita": "Media",
        "id_gruppo": 7,
        "link": "https://www.bbc.com/news/articles/c7955ewj7gwo?at_medium=RSS&at_campaign=rss",
        "orario": "12:54",
        "timestamp": 1772625267.0,
        "contenuto_esteso": "The Met Police says three men are suspected of assisting Chinese intelligence services in the UK."
    },
    {
        "testata": "Deutsche Welle",
        "lingua_originale": "en",
        "titolo_orig": "US, Ecuador launch joint anti-drug operation",
        "testo_it": "USA ed Ecuador lanciano operazione congiunta per contrastare traffico droga.",
        "priorita": "Media",
        "id_gruppo": 8,
        "link": "https://www.dw.com/en/us-ecuador-launch-joint-anti-drug-operation/a-76213849?maca=en-rss-en-world-4025-rdf",
        "orario": "12:15",
        "timestamp": 1772622900.0,
        "contenuto_esteso": "Ecuador has joined a drug interdiction operation commanded by the US aimed at disrupting the transit of cocaine produced in Latin America."
    },
    {
        "testata": "Deutsche Welle",
        "lingua_originale": "en",
        "titolo_orig": "Did the US‑Israel strikes on Iran break international law?",
        "testo_it": "Gli attacchi USA-Israele contro Iran violano diritto internazionale, secondo esperti.",
        "priorita": "Alta",
        "id_gruppo": 1,
        "link": "https://www.dw.com/en/did-the-us‑israel-strikes-on-iran-break-international-law/a-76203543?maca=en-rss-en-world-4025-rdf",
        "orario": "12:02",
        "timestamp": 1772622120.0,
        "contenuto_esteso": "From disputed self‑defense claims to the killing of Iran’s leader, legal experts say the US‑Israeli attack defies UN rules. Iran’s response and mixed global reactions highlight fears that international law is eroding."
    },
    {
        "testata": "Deutsche Welle",
        "lingua_originale": "en",
        "titolo_orig": "Iran attacks on Gulf oil and gas sites trigger energy fears",
        "testo_it": "Attacchi Iran a siti energetici nel Golfo aumentano timori per forniture globali.",
        "priorita": "Alta",
        "id_gruppo": 1,
        "link": "https://www.dw.com/en/iran-attacks-on-gulf-oil-and-gas-sites-trigger-energy-fears/a-76199281?maca=en-rss-en-world-4025-rdf",
        "orario": "07:47",
        "timestamp": 1772606820.0,
        "contenuto_esteso": "Iranian attacks on regional refineries and gas facilities, and oil tankers are increasing global energy supply fears, risking major economic fallouts from Asia to Europe, and leaving consumers bracing for higher prices."
    },
    {
        "testata": "France 24",
        "lingua_originale": "en",
        "titolo_orig": "Iranian warship sinks off Sri Lanka, 32 sailors rescued",
        "testo_it": "Nave da guerra iraniana affonda al largo Sri Lanka; 32 marinai tratti in salvo.",
        "priorita": "Media",
        "id_gruppo": 9,
        "link": "https://www.france24.com/en/middle-east/20260304-iranian-warship-sinks-off-sri-lanka-32-sailors-rescued",
        "orario": "12:27",
        "timestamp": 1772623659.0,
        "contenuto_esteso": "An Iranian warship, the IRIS Dena, has sunk off the ​coast of Sri Lanka, with the Sri Lankan authorities saying on Wednesday they had rescued 32 people who were on board and recovered ​several bodies ‌from the sea."
    },
    {
        "testata": "France 24",
        "lingua_originale": "en",
        "titolo_orig": "\"US lawmakers' efforts to curb Trump's ability to continue war almost sure to fail\"",
        "testo_it": "Sforzi USA per limitare potere di guerra di Trump quasi certamente falliranno.",
        "priorita": "Alta",
        "id_gruppo": 1,
        "link": "https://www.france24.com/en/us-lawmakers-efforts-to-curb-trump-s-ability-to-continue-war-almost-sure-to-fail",
        "orario": "11:56",
        "timestamp": 1772621778.0,
        "contenuto_esteso": "Lawmakers in the U.S. Senate are set to vote on March 4th on a bipartisan war powers resolution aiming to stop the military campaign against Iran and require that any ​hostilities against it ‌be authorised by Congress. This comes as Trump faces little voter support for the war. But lawmakers' efforts to curb Trump's ability to \"goad alone with Israel in this war against Iran are almost sure to fail\", warns FRANCE 24's Douglas Herbert."
    },
    {
        "testata": "France 24",
        "lingua_originale": "en",
        "titolo_orig": "Iran war opens cracks within Trump's MAGA base",
        "testo_it": "Guerra Iran apre crepe nella base elettorale MAGA di Trump, calano i consensi.",
        "priorita": "Alta",
        "id_gruppo": 1,
        "link": "https://www.france24.com/en/iran-war-opens-cracks-within-trump-s-maga-base",
        "orario": "11:52",
        "timestamp": 1772621558.0,
        "contenuto_esteso": "President Trump has launched into a war while he’s facing some of the lowest approval ratings of his political career. A recent poll showed that just one in four Americans approved of his attack on Iran. But it’s not just the general American public: The war is also beginning to show some cracks in support from his die-hard “Make American Great Again” base."
    },
    {
        "testata": "Swissinfo",
        "lingua_originale": "en",
        "titolo_orig": "Inflazione: stabile allo 0,1% in febbraio in Svizzera - SWI swissinfo.ch",
        "testo_it": "Inflazione in Svizzera stabile allo 0,1% nel mese di febbraio.",
        "priorita": "Bassa",
        "id_gruppo": 10,
        "link": "https://news.google.com/rss/articles/CBMingFBVV95cUxPZDVfelNvQWFlTHF6Y3Vjem9ZODBWbnZmTjZMUmZsWUZxbldoMENQSHNzbzdnMGFIajFidlVoeGFXSWdtcmpZTnUxUm5IUjRtaFIwdGZDNkw5REdhRllHNGtGVUJVWUl4ZS1ZNEFWcmRxSnBhckdRQ0x0eDNrMEhiemZXekhYRHNscmt0OE41b0w5RG56N0phNGUyUVgyUQ?oc=5",
        "orario": "08:10",
        "timestamp": 1772608222.0,
        "contenuto_esteso": "Inflazione: stabile allo 0,1% in febbraio in Svizzera SWI swissinfo.ch"
    },
    {
        "testata": "Swissinfo",
        "lingua_originale": "en",
        "titolo_orig": "On: vendite di scarpe volano, fatturato supera i 3 miliardi - SWI swissinfo.ch",
        "testo_it": "Vendite record per il marchio di scarpe On, fatturato oltre 3 miliardi.",
        "priorita": "Bassa",
        "id_gruppo": 11,
        "link": "https://news.google.com/rss/articles/CBMiowFBVV95cUxQV2xveDRXWk52RjNMVUwtTjVPQVR4ZW9xTGtSaTF2a2RRd0dGLV80akZKU3ZuTmVuazlqdE15R2RUUUluZ3NVc2duUXNONnQ0S2hrT1J3dDR0UjdSUzVwcG5SZlJkS1BUTnpPNjY3LVBYeS1NLUNtQjhCNmtDbkZ3UldIcndRdmhGdnJZSG05ZDFGU1JTT0Q3bTZqbHlXdlNuM1dV?oc=5",
        "orario": "16:00 - 3 Marzo",
        "timestamp": 1772550000.0,
        "contenuto_esteso": "On: vendite di scarpe volano, fatturato supera i 3 miliardi SWI swissinfo.ch"
    },
    {
        "testata": "The New York Times",
        "lingua_originale": "en",
        "titolo_orig": "Live Updates: Turkey Says NATO Shot Down Iranian Missile Heading to Turkish Airspace",
        "testo_it": "Turchia: NATO ha abbattuto missile iraniano diretto verso spazio aereo turco.",
        "priorita": "Alta",
        "id_gruppo": 2,
        "link": "https://www.nytimes.com/live/2026/03/04/world/iran-war-israel-lebanon-trump",
        "orario": "12:54",
        "timestamp": 1772625295.0,
        "contenuto_esteso": "An attack on Turkey, a NATO member that shares a border with Iran, would mark a major escalation in Iran’s retaliation for the U.S. and Israeli assault."
    },
    {
        "testata": "The New York Times",
        "lingua_originale": "en",
        "titolo_orig": "Ayatollah Ali Khamenei’s Son Emerges as Leading Choice to Be His Successor",
        "testo_it": "Figlio di Khamenei emerge come favorito per la successione alla guida dell'Iran.",
        "priorita": "Alta",
        "id_gruppo": 1,
        "link": "https://www.nytimes.com/2026/03/03/world/middleeast/iran-mojtaba-khamenei-successor.html",
        "orario": "01:54",
        "timestamp": 1772585663.0,
        "contenuto_esteso": "Mojtaba Khamenei, son of the slain former leader of Iran, in Tehran in 2019."
    },
    {
        "testata": "The New York Times",
        "lingua_originale": "en",
        "titolo_orig": "Global Leaders Brace for the Fallout From a Fast Metastasizing War",
        "testo_it": "Leader mondiali preparano conseguenze guerra rapida che si sta diffondendo.",
        "priorita": "Alta",
        "id_gruppo": 1,
        "link": "https://www.nytimes.com/2026/03/04/world/europe/iran-trump-world-reaction.html",
        "orario": "11:37",
        "timestamp": 1772620642.0,
        "contenuto_esteso": "A woman cries after seeing the rubble from a building that was hit by airstrikes in Tehran on Tuesday."
    },
    {
        "testata": "The Guardian",
        "lingua_originale": "en",
        "titolo_orig": "South Sudan risks return to full-blown civil war as violence escalates",
        "testo_it": "Sud Sudan rischia guerra civile per escalation violenze vicino confine con Sudan.",
        "priorita": "Media",
        "id_gruppo": 13,
        "link": "https://www.theguardian.com/world/2026/mar/03/south-sudan-risks-return-civil-war-violence-escalates",
        "orario": "15:49 - 3 Marzo",
        "timestamp": 1772549376.0,
        "contenuto_esteso": "At least 169 killed in raid near Sudan border as clashes between government and opposition forces intensify South Sudan is reeling from an escalating conflict between the government-aligned army and opposition forces and allied groups that observers say risks returning the country to a full-blown civil war. Violent confrontations in the world’s youngest country between the military, which is loyal to President Salva Kiir, and insurgents believed to be allied to the suspended vice-president, Riek Machar, have increased in recent weeks. Continue reading..."
    },
    {
        "testata": "The Guardian",
        "lingua_originale": "en",
        "titolo_orig": "‘Imperialist undertones’: global south condemns US-Israeli war with Iran",
        "testo_it": "Sud globale condanna guerra USA-Israele contro Iran; Cina critica l'uccisione leader.",
        "priorita": "Alta",
        "id_gruppo": 1,
        "link": "https://www.theguardian.com/world/2026/mar/03/global-south-condemns-us-israeli-war-with-iran",
        "orario": "13:11 - 3 Marzo",
        "timestamp": 1772539877.0,
        "contenuto_esteso": "China calls it unacceptable to ‘kill leader of sovereign state’, while South Africa questions ‘pre-emptive’ justification Middle East crisis – live updates The US-Israeli war on Iran has been condemned as illegal across much of the global south, with China saying it was unacceptable to “blatantly kill the leader of a sovereign state”. Many countries objected that negotiations between the US and Iran over its nuclear programme and missile capability were not given a chance to succeed before Washington and Israel began bombing, and analysts often saw the war in terms of a colonial-style exercise of might. Continue reading..."
    },
    {
        "testata": "The Guardian",
        "lingua_originale": "en",
        "titolo_orig": "Ghana says at least 55 of its people killed after Russia ‘lured’ them to fight Ukraine",
        "testo_it": "Ghana: 55 cittadini uccisi in Ucraina dopo essere stati 'adescati' dalla Russia.",
        "priorita": "Media",
        "id_gruppo": 14,
        "link": "https://www.theguardian.com/world/2026/feb/27/ghana-men-killed-fight-russia-ukraine",
        "orario": "16:42 - 27 Febbraio",
        "timestamp": 1772206959.0,
        "contenuto_esteso": "Foreign minister says 272 Ghanaians are thought to have been drawn into battle since 2022, after he visited Kyiv At least 55 Ghanaians have been killed in Russia’s war with Ukraine after being “lured into battle”, Ghana’s foreign minister has said after a visit to Kyiv in which officials raised the issue of Russian recruitment of African people. Reports of African men being attracted to Russia by promises of jobs and ending up on Ukraine’s frontlines have become more frequent in recent months, creating tensions between Moscow and some of the countries involved. Continue reading..."
    },
    {
        "testata": "Le Monde",
        "lingua_originale": "fr",
        "titolo_orig": "EN DIRECT, Iran : un missile balistique tiré d’Iran et visant l’espace aérien turc a été détruit par l’OTAN ; Ankara met en garde Téhéran",
        "testo_it": "EN DIRECT: NATO distrugge missile balistico iraniano diretto verso spazio aereo turco.",
        "priorita": "Alta",
        "id_gruppo": 2,
        "link": "https://www.lemonde.fr/international/live/2026/03/04/en-direct-iran-israel-annonce-avoir-abattu-un-avion-de-chasse-iranien-teheran-ne-veut-pas-negocier-avec-les-etats-unis-et-se-dit-pret-pour-une-longue-guerre_6668663_3210.html",
        "orario": "09:21",
        "timestamp": 1772612480.0,
        "contenuto_esteso": "A la suite d’une frappe, à Téhéran, le 4 mars 2026."
    },
    {
        "testata": "Le Monde",
        "lingua_originale": "fr",
        "titolo_orig": "Pour Donald Trump, la guerre en Iran opère un tri entre bons et mauvais pays européens",
        "testo_it": "Trump: guerra in Iran opera un filtro tra paesi europei buoni e cattivi.",
        "priorita": "Alta",
        "id_gruppo": 6,
        "link": "https://www.lemonde.fr/international/article/2026/03/04/pour-donald-trump-la-guerre-en-iran-opere-un-tri-entre-bons-et-mauvais-pays-europeens_6669429_3210.html",
        "orario": "01:00",
        "timestamp": 1772582405.0,
        "contenuto_esteso": "Le chancelier allemand, Friedrich Merz, et le président américain, Donald Trump, lors d’un entretien dans le bureau Ovale de la Maison blanche, à Washington, le 3 mars 2026."
    },
    {
        "testata": "Le Monde",
        "lingua_originale": "fr",
        "titolo_orig": "En Israël, la satisfaction sur le bilan des premiers jours de la guerre",
        "testo_it": "In Israele soddisfazione per bilancio primi giorni di guerra contro l'Iran.",
        "priorita": "Alta",
        "id_gruppo": 1,
        "link": "https://www.lemonde.fr/international/article/2026/03/04/en-israel-la-satisfaction-sur-le-bilan-des-premiers-jours-de-la-guerre_6669478_3210.html",
        "orario": "09:30",
        "timestamp": 1772613004.0,
        "contenuto_esteso": "Le chef d’état-major Eyal Zamir, le premier ministre Benyamin Nétanyahou, et son ministre de la défense, Israel Katz, sur la base aérienne de Palmachim, en Israël, le 3 mars 2026."
    },
    {
        "testata": "Libération",
        "lingua_originale": "fr",
        "titolo_orig": "EN DIRECT - Guerre au Moyen-Orient : les funérailles de Khamenei reportées en raison de «l’affluence», selon le régime",
        "testo_it": "Funerale di Khamenei rinviato a Teheran per 'affluenza' record, secondo il regime.",
        "priorita": "Alta",
        "id_gruppo": 1,
        "link": "https://www.liberation.fr/international/moyen-orient/guerre-au-moyen-orient-les-premiers-rapatries-francais-ont-atterri-a-paris-israel-20260304_GNERINNNDJFBJEOI2DAEFOLBY4/",
        "orario": "12:56",
        "timestamp": 1772625406.0,
        "contenuto_esteso": "Une banderole à l'effigie de Khamenei, le 4 mars à Téhéran."
    },
    {
        "testata": "Libération",
        "lingua_originale": "fr",
        "titolo_orig": "Golfe en guerre : le détroit d’Ormuz au cœur d’un choc énergétique mondial",
        "testo_it": "Golfo in guerra: Stretto di Hormuz al centro di shock energetico globale.",
        "priorita": "Alta",
        "id_gruppo": 1,
        "link": "https://www.liberation.fr/international/golfe-en-guerre-le-detroit-dormuz-au-coeur-dun-choc-energetique-mondial-20260303_WXLNBSRGAZB2LPDZVQR4CPKNOA/",
        "orario": "19:51 - 3 Marzo",
        "timestamp": 1772563909.0,
        "contenuto_esteso": "Des tankers dans le détroit d'Ormuz, au large de Fujaïrah (Emirats arabes unis), le 3 mars 2026."
    },
    {
        "testata": "Libération",
        "lingua_originale": "fr",
        "titolo_orig": "Bombardement de l’école de Minab en Iran : que montrent les images des funérailles des victimes ?",
        "testo_it": "Immagini dai funerali delle vittime del bombardamento di una scuola a Minab, Iran.",
        "priorita": "Alta",
        "id_gruppo": 1,
        "link": "https://www.liberation.fr/checknews/bombardement-de-lecole-de-minab-en-iran-que-montrent-les-images-des-funerailles-des-victimes-20260303_N7CVDW2W35DU7CTQWHV4JOHLLQ/",
        "orario": "19:16 - 3 Marzo",
        "timestamp": 1772561766.0,
        "contenuto_esteso": "Lors des funérailles de victimes des bombardements à Minab, ce mardi 3 mars."
    },
    {
        "testata": "Al Jazeera",
        "lingua_originale": "en",
        "titolo_orig": "Why are the US and Israel framing the ongoing conflict as a religious war?",
        "testo_it": "Perché USA e Israele inquadrano il conflitto come guerra religiosa (Armageddon)?",
        "priorita": "Alta",
        "id_gruppo": 1,
        "link": "https://www.aljazeera.com/news/2026/3/4/why-are-the-us-and-israel-framing-the-ongoing-conflict-as-a-religious-war?traffic_source=rss",
        "orario": "12:54",
        "timestamp": 1772625299.0,
        "contenuto_esteso": "US troops reportedly told the war in Iran is intended to bring about biblical end times, Armageddon."
    },
    {
        "testata": "Al Jazeera",
        "lingua_originale": "en",
        "titolo_orig": "‘Israel at its peak power in the Middle East and it’s downhill from here’",
        "testo_it": "Analisi: Israele al picco di potenza in Medio Oriente, da qui solo in discesa.",
        "priorita": "Media",
        "id_gruppo": 1,
        "link": "https://www.aljazeera.com/video/quotable/2026/3/4/israel-is-at-its-peak-power-in-the-middle-east-and-its-downhill-from-here?traffic_source=rss",
        "orario": "12:50",
        "timestamp": 1772625024.0,
        "contenuto_esteso": "'Israel is at its peak power in the Middle East and it's downhill from here'"
    },
    {
        "testata": "Al Jazeera",
        "lingua_originale": "en",
        "titolo_orig": "Nepal election 2026: Who are the contenders and what’s at stake?",
        "testo_it": "Elezioni in Nepal: contendenti e posta in gioco nel voto cruciale di giovedì.",
        "priorita": "Bassa",
        "id_gruppo": 15,
        "link": "https://www.aljazeera.com/news/2026/3/4/nepal-election-2026-who-are-the-contenders-and-whats-at-stake?traffic_source=rss",
        "orario": "12:46",
        "timestamp": 1772624801.0,
        "contenuto_esteso": "Nepal is set to ‌vote on Thursday in pivotal election that comes months after historic protests toppled the government."
    },
    {
        "testata": "South China Morning Post",
        "lingua_originale": "en",
        "titolo_orig": "London police arrest 3 men on suspicion of spying for China",
        "testo_it": "Polizia di Londra arresta 3 uomini sospettati di spionaggio per conto della Cina.",
        "priorita": "Media",
        "id_gruppo": 7,
        "link": "https://www.scmp.com/news/world/europe/article/3345462/london-police-arrest-3-men-suspicion-spying-china?utm_source=rss_feed",
        "orario": "12:59",
        "timestamp": 1772625571.0,
        "contenuto_esteso": "Three men suspected of spying for China were arrested on Wednesday, London police said.\nThe three were arrested for allegedly assisting a foreign intelligence service in violation of the National Security Act of 2023.\nPolice did not name the suspects because they have not been charged. But they said one was a 39-year-old arrested in London, another was a 68-year-old arrested in Powys, Wales and the third, a 43-year-old, was arrested in Pontyclun, Wales.\nThey are the latest in a number of arrests..."
    },
    {
        "testata": "South China Morning Post",
        "lingua_originale": "en",
        "titolo_orig": "Air freight costs for China shippers tipped to rise 30% as Middle East airspace shuts down",
        "testo_it": "Costi trasporto aereo Cina aumenteranno 30% per chiusura spazio aereo Medio Oriente.",
        "priorita": "Alta",
        "id_gruppo": 1,
        "link": "https://www.scmp.com/business/article/3345461/air-freight-costs-china-shippers-tipped-rise-30-middle-east-airspace-shuts-down?utm_source=rss_feed",
        "orario": "12:54",
        "timestamp": 1772625278.0,
        "contenuto_esteso": "Air freight costs for China-reliant shippers may rise by up to 30 per cent due to the suspension of Middle East air routes triggered by US and Israeli strikes on Iran, a Hong Kong-based logistics association said.\nThe Hong Kong Association of Freight Forwarding & Logistics made the estimate based on “market feedback” since the strikes began on Saturday, the trade group told the South China Morning Post in an emailed statement.\nMost of the group’s 303 corporate members operate in mainland..."
    },
    {
        "testata": "South China Morning Post",
        "lingua_originale": "en",
        "titolo_orig": "Germany’s Merz lacked ‘solidarity’ amid silence during Trump attacks: Spain",
        "testo_it": "Spagna accusa Germania: Merz mancò di 'solidarietà' contro attacchi di Trump.",
        "priorita": "Alta",
        "id_gruppo": 6,
        "link": "https://www.scmp.com/news/world/europe/article/3345459/germanys-merz-lacked-solidarity-amid-silence-during-trump-attacks-spain?utm_source=rss_feed",
        "orario": "12:42",
        "timestamp": 1772624550.0,
        "contenuto_esteso": "Spanish Foreign Minister José Manuel Albares on Wednesday accused German Chancellor Friedrich Merz of failing to show “solidarity” with Madrid in the face of criticism from US President Donald Trump.\nAlbares told broadcaster RTVE that he has communicated his “surprise” over Merz’s response to Trump’s tirade against Spain in a White House meeting on Tuesday.\n“When you share a currency, a common trade policy and a common market with another country, you expect the same solidarity that Spain showed..."
    },
    {
        "testata": "Times of India",
        "lingua_originale": "en",
        "titolo_orig": "Canada announces $100 million scholarships for Indian students, introduces 'hybrid study locations'",
        "testo_it": "Canada stanzia 100M$ in borse di studio per studenti indiani, introduce studio ibrido.",
        "priorita": "Bassa",
        "id_gruppo": 16,
        "link": "https://timesofindia.indiatimes.com/world/rest-of-world/canada-announces-100-million-scholarships-for-indian-students-introduces-hybrid-study-locations/articleshow/129025046.cms",
        "orario": "12:47",
        "timestamp": 1772624836.0,
        "contenuto_esteso": ""
    },
    {
        "testata": "Times of India",
        "lingua_originale": "en",
        "titolo_orig": "‘Very alarming’: Laura Loomer says she feels ‘unsafe’ seeing Muslim workers at US airport amid Iran war",
        "testo_it": "Attivista Loomer si sente 'insicura' vedendo dipendenti musulmani negli aeroporti USA.",
        "priorita": "Media",
        "id_gruppo": 1,
        "link": "https://timesofindia.indiatimes.com/world/us/very-alarming-laura-loomer-says-she-feels-unsafe-seeing-muslim-workers-at-us-airport-amid-iran-war/articleshow/129025760.cms",
        "orario": "12:43",
        "timestamp": 1772624618.0,
        "contenuto_esteso": "Far-right activist Laura Loomer expressed feeling \"unsafe\" due to the number of Muslim workers at US airports, citing her experience in Atlanta. She questioned why Muslims are employed as TSA agents and airport staff, stating her belief that there are \"too many Muslims in America."
    },
    {
        "testata": "Times of India",
        "lingua_originale": "en",
        "titolo_orig": "'I feel abandoned': Indian-American CEO stranded in Dubai says India rescuing citizens but US doing nothing",
        "testo_it": "CEO indiano-americano bloccato a Dubai: USA non fanno nulla, India salva cittadini.",
        "priorita": "Media",
        "id_gruppo": 1,
        "link": "https://timesofindia.indiatimes.com/world/us/i-feel-abandoned-indian-american-ceo-stranded-in-dubai-says-india-rescuing-citizens-but-us-doing-nothing/articleshow/129024652.cms",
        "orario": "11:47",
        "timestamp": 1772621257.0,
        "contenuto_esteso": ""
    },
    {
        "testata": "The Hill",
        "lingua_originale": "en",
        "titolo_orig": "Trump’s 401(k) proposal could be a major step toward retirement security",
        "testo_it": "Proposta 401(k) di Trump potrebbe migliorare sicurezza pensionistica per lavoratori.",
        "priorita": "Bassa",
        "id_gruppo": 17,
        "link": "https://thehill.com/opinion/finance/5764729-trumps-401k-proposal-could-be-a-major-step-toward-retirement-security/",
        "orario": "12:30",
        "timestamp": 1772623800.0,
        "contenuto_esteso": "Getting all workers into retirement savings plans, particularly low-earners, remains a formidable challenge."
    },
    {
        "testata": "The Hill",
        "lingua_originale": "en",
        "titolo_orig": "In Iran, regime change is the only goal that ever made sense",
        "testo_it": "In Iran, il cambio di regime è l'unico obiettivo sensato per l'attacco USA.",
        "priorita": "Alta",
        "id_gruppo": 1,
        "link": "https://thehill.com/opinion/national-security/5763662-in-iran-regime-change-was-the-only-goal-that-ever-made-sense/",
        "orario": "12:00",
        "timestamp": 1772622000.0,
        "contenuto_esteso": "The only way a U.S. attack on Iran ever made sense was is if its goal was regime change. If the intention is, for example, to compel Iran to do a “deal” then there was no point in attacking. Under the current circumstances, no deal is worth the cost of lifting sanctions that would give..."
    },
    {
        "testata": "Politico",
        "lingua_originale": "en",
        "titolo_orig": "'A perfect storm is lining up for Texas Democrats'",
        "testo_it": "Per i Democratici del Texas si profila una 'tempesta perfetta' alle elezioni.",
        "priorita": "Bassa",
        "id_gruppo": 19,
        "link": "https://www.politico.com/news/2026/03/04/talarico-won-his-primary-what-happens-next-is-outside-his-control-00811456",
        "orario": "08:53",
        "timestamp": 1772610798.0,
        "contenuto_esteso": "James Talarico's charmed political journey has broken his way at almost every juncture of his career, from “ The Joe Rogan Experience ” invite as he was weighing a Senate bid last summer to his star turn in Texas’ quorum break to a fundraising windfall over a spiked Stephen Colbert interview in the primary's homestretch. But as he gave his not-quite-victory speech late Tuesday night, Talarico faced a more uncertain future than he had hoped. The Associated Press eventually called the election for him hours later, though voting problems in Crockett's home base of Dallas County delayed the result. And suddenly, it looks like he could face a much tougher opponent than he’d banked on in the general election. Talarico and Democrats had hoped for months that the preacher would get to face scandal-tarred Texas Attorney General Ken Paxton, but Sen. John Cornyn (R-Texas), a less objectionable general-election foil, had outperformed expectations and fought him to a draw, forcing a runoff. For the disciplined and studious Democrat who can commit scripture and prepared remarks to memory in a matter of minutes, and who is known by aides to linger over edits to social media posts and ads, the unknown outcome of the runoff is an unwelcome twist, the seemingly rare thing he cannot control. Even with a 12-week head start on whomever voters select as his opponent in a brass-knuckled, dregs-scraping, cash-consuming GOP runoff, Talarico could still face a four-term incumbent with a long track record of big general-election wins. Amid a legal dispute over voting precinct hours in Dallas County, Talarico did not quite declare victory in a short speech just after midnight local time, when he was leading the race but before the Associated Press called it. “We are still waiting for an official call, but we are confident in this movement we've built together,” he said after lamenting what he called “voter suppression.” “We are not just trying to win an election,” Talarico said at his rally in Austin. “We are trying to fundamentally change our politics, and it's working.” Earlier Tuesday, a district judge permitted the Dallas County Democratic Party to extend polling hours until 9 p.m. central, but the Texas Supreme Court granted Attorney General Ken Paxton's request to set aside the votes of those people who were not in line by 7 p.m. The polling problems are just the latest in a long history of voter suppression and voting rights battles in the state — ones that have particularly impacted Black and Hispanic voters. Crockett first gained national attention as a state representative battling against the Texas GOP’s move to pass a law that added new restrictions on voting, an issue once again in the spotlight as her Senate campaign came to a close. In a statement earlier in the evening, Talarico's campaign acknowledged that they were “deeply concerned about the reports of voters being turned away from the polls in Dallas and Williamson counties following the GOP's implementation of precinct-specific voting locations for Election Day.” Talarico ran well in heavily white and Hispanic areas on Tuesday, but has conceded he has work to do with Black voters if he’s going to win in November — an effort that could be complicated by the sour final note of voter confusion. The final stretch of the contest pitted Talarico’s and Crockett’s supporters against each other in bitter feuds, often along racial lines, that played out on social media platforms like TikTok and X. Those debates focused on whether Democrats believed Crockett, a Black representative from Dallas, could be elected in a deep-red state — as well as over a claim made by a social media influencer that Talarico had described a former opponent as a “mediocre Black man,” comments he says were misconstrued. Still, his strong performance against Crockett has jolted Democratic hopes of winning Texas for the first time in more than a generation, forging a wider than expected path to flipping the Senate — and out of the wilderness. “I’d be very worried if I were the national Republican Party after tonight,” said Emily Cherniack, the founder and CEO of New Politics, and a longtime Talarico ally. “Strong turnout, especially among Latino voters, signals real dissatisfaction with Republicans in power. That’s a huge warning sign for November for them.” Up until Tuesday, Senate Democrats had staked their chances of flipping the Republican-controlled Senate on just four states: North Carolina, Maine, Ohio and Alaska. But now, some Democrats believe Talarico can cobble together a winning coalition in the most improbable of states — no Democrat has a Senate seat in Texas since 1988 — based on his class-focused message seeking to unite voters across parties. “A perfect storm is lining up for Texas Democrats,” said Mark McKinnon, the former Texas media operative who started out advising Democrat Ann Richards on her gubernatorial campaigns before switching to Republican George W. Bush in 1997. “They have a nominee who can appeal to moderates and soft Republicans. Talarico could be Moses who leads the Lone Star Democrats out of the desert they've been in for 35 years.” Public and private polls have mostly shown close races in either matchup; Talarico would start off with the edge over Paxton but trail Cornyn. “It is still a massive mountain to climb, but this doesn’t hurt the effort,” one former staffer on Kamala Harris’ presidential campaign said of Talarico’s win. Talarico has argued that he can beat either foe. “I think both of them are extraordinarily weak,” Talarico said in an interview with POLITICO just days before Election Day. “Paxton and Cornyn, they're different. Paxton was guilty of illegal corruption. That's why my colleagues and I impeached him in the Texas House. But Cornyn is guilty of legalized corruption. He was the deciding vote on the Big, Ugly, Bill which kicked millions of Texas off their health care, took food out of the mouths of hungry Texas kids all to give tax breaks to his donors. Both of them are guilty of using their public offices to enrich their donors — Ken Paxton in an illegal way, but John Cornyn in a legal way. I look forward to prosecuting the case against either of them — whoever makes it out.”"
    },
    {
        "testata": "Politico",
        "lingua_originale": "en",
        "titolo_orig": "Cornyn is still in the fight. Will Trump finally endorse him?",
        "testo_it": "Cornyn resiste nel primario GOP Texas; attesa per l'endorsement di Trump.",
        "priorita": "Bassa",
        "id_gruppo": 19,
        "link": "https://www.politico.com/news/2026/03/04/cornyn-texas-results-trump-endorsement-00811453",
        "orario": "08:05",
        "timestamp": 1772607935.0,
        "contenuto_esteso": "Sen. John Cornyn defied expectations in the Texas GOP primary on Tuesday. National Republicans believe his unexpectedly strong showing may be enough for President Donald Trump to endorse the embattled incumbent. Trump has privately intimated that he will soon get involved in the Texas Senate race after rebuffing endorsement pleas from both candidates for months, according to a GOP strategist close to the White House who was granted anonymity to speak freely. For months, party leaders worried that Trump would back state Attorney General Ken Paxton, a longtime ally of the president, especially if he dominated in Tuesday’s primary. Then came the results that had Cornyn neck-and-neck with Paxton. With that outcome, the strategist said, it would be “very surprising” if Trump backed Paxton. The stakes are high for Republicans, who fear control of the Senate is hanging in the balance. The GOP hoped to avoid state Rep. James Talarico clinching the Democratic nomination because they see him as able to draw away moderate Republican voters. Republicans “should take him seriously,” said another close Trump administration ally, granted anonymity to be candid. Talarico is a “big reason for Trump to get in for Cornyn and end this thing,” the ally said, especially to free up massive amounts of money that could be spent instead on competitive Senate races in Michigan and Georgia. National Republicans estimated they would have to spend $200 million to protect Cornyn in the runoff. But the GOP strategist shrugged off the price tag. “Look, it will probably cost some money,” the person said. “It's just money, we have a lot of it.” Tuesday’s results were the best-case scenario for establishment Republicans, who worried Cornyn would finish far enough behind Paxton that it would be a slog for him — and a tough sell for a president who hates to back losers. The Texas GOP Senate primary has become a referendum on the future of the Republican Party, testing the strength of the conservative grassroots against the establishment wing. While the MAGA base kept the four-term incumbent — who nearly became Senate majority leader — from getting a majority of the primary vote, the results show the old Republican establishment isn’t quite dead yet. Cornyn’s narrow lead over Paxton was powered by even performances across the state. Even in the most heavily Republican counties where Paxton might have expected to benefit from a MAGA base, the incumbent senator largely held his own: Across more than 110 mostly rural counties that Trump won by at least 50 points in 2024 and were reporting complete results as of early Wednesday morning, Paxton built up only the narrowest of leads, 44 percent to just shy of 40 percent for Cornyn. Meanwhile, Cornyn strengthened his advantage in the more traditional white-collar suburbs, leading by double digits in Travis and Dallas counties as results continued to come in early Wednesday morning. The senator, speaking to reporters on Election Night in Austin, said Republican voters’ choice is “crystal clear.” “I refuse to allow a flawed, self-centered, and shameless candidate like Ken Paxton risk everything we've worked so hard to build over these many years,” he said. “There is simply too much at stake.\" Republicans are well aware that overall control of the Senate may be at risk. Cornyn’s allies warn that scandal-plagued Paxton turns off general election voters, especially if Talarico is their opponent. During Paxton’s decade as attorney general, he faced an impeachment by the GOP-led Texas state House, ethics complaints, a federal securities fraud investigation and a recent divorce complete with allegations of infidelity. Now Paxton is facing another 12 weeks going up against the wrath — and war chest — of the Washington establishment. “John Cornyn spent around $100 million trying to buy this seat,” Paxton told his supporters at a watch party after the race was called. “We spent around $5 million… We prove something they’ll never understand in Washington: Texas is not for sale.” One question is which candidate the voters who backed Rep. Wesley Hunt, who finished a distant third place, will support now — or whether they turn out at all for the May runoff. Lone Star Liberty, a pro-Paxton super PAC, in a memo circulated ahead of Tuesday's election, shrugged off threats that Cornyn would succeed in the runoff by continuing to hammer the attorney general on his litany of scandals, arguing they had nothing new to offer. “Cornyn’s talk of ‘unleashing’ new attacks’ in the runoff is bluster,” the memo states. “The truth is that from day one, his forces fired every bullet they had. There are no new attacks left — only more of the same, at ever-greater cost and with ever-diminishing returns.” Senate Republican operatives – who had entered the night expecting the race to head to a runoff, but unsure of how Cornyn would track against Paxton – were exultant as the incumbent maintained a narrow lead well into the night. A Republican working on Senate campaigns, granted anonymity to speak freely, said Cornyn “proved to be formidable” on Tuesday — bolstering the establishment GOP argument that he is “the most electable” as the party braces for a battle against Talarico. Talarico's lead \"reaffirms the need to have Cornyn as the nominee. Can't risk this to Paxton,\" the GOP operative close to the White House said. Yet some Republicans conceded Cornyn has a tricky path to navigate. He’ll have to square off again with the conservative primary voters who make up Paxton's base. “Runoffs are extremely unpredictable, and head-to-head it could be anyone’s ballgame,\" said Republican strategist Jeff Burton. Dasha Burns, Lisa Kashinsky, Alec Hernandez, Jessica Piper and Erin Doherty contributed reporting"
    },
    {
        "testata": "Politico",
        "lingua_originale": "en",
        "titolo_orig": "Talarico defeats Crockett in Texas Senate Democratic primary",
        "testo_it": "Talarico vince primarie democratiche Senato Texas, preferito dai leader di partito.",
        "priorita": "Bassa",
        "id_gruppo": 19,
        "link": "https://www.politico.com/news/2026/03/04/james-talarico-wins-texas-senate-primary-00811090",
        "orario": "07:38",
        "timestamp": 1772606335.0,
        "contenuto_esteso": "State Rep. James Talarico won the Texas Senate Democratic primary, defeating Rep. Jasmine Crockett and giving party leaders the candidate they had quietly seen as the stronger option to flip the ruby-red state. The race was defined by questions of electability and simmering racial tensions , as Talarico and Crockett worked to reassemble the party’s fractured multiracial coalition. That carried over through Tuesday, with both candidates raising concerns that voters had been disenfranchised in Crockett’s home base of Dallas County, which includes a large number of Black voters. The legal dispute over voting precincts in Dallas could cast a shadow over his victory. Crockett told her supporters not to expect a final call on election night. Talarico, a progressive Seminarian, took a big-tent approach to his campaign by appealing to voters from both parties and independents. He will face off against either Sen. John Cornyn or Texas Attorney General Ken Paxton, who is mounting a right wing challenge to the four-term incumbent. Texas Democrats have failed to win statewide in three decades, but they believe they have a rare opening to flip the Senate seat in November, due to backlash to the Trump administration’s mass deportation efforts and handling of the economy — especially if Paxton emerges from the GOP runoff. There has been scant nonpartisan public polling in the general election, but a recent memo from the National Republican Senatorial Committee shows Cornyn ahead of Talarico by three points, while Talarico would lead Paxton by three points."
    },
    {
        "testata": "Limes",
        "lingua_originale": "it",
        "titolo_orig": "Il Qatar e il Kurdistan iracheno si schierano contro l'Iran e altre notizie interessanti",
        "testo_it": "Qatar e Kurdistan iracheno contro l'Iran: rassegna geopolitica del giorno.",
        "priorita": "Media",
        "id_gruppo": 1,
        "link": "https://www.limesonline.com/rubriche/il-mondo-oggi/guerra-iran-mojtaba-khamenei-usa-israele-qatar-spagna-ecuador-sudan-etiopia-21346457/",
        "orario": "11:23",
        "timestamp": 1772619780.0,
        "contenuto_esteso": "La rassegna geopolitica della giornata."
    },
    {
        "testata": "Limes",
        "lingua_originale": "it",
        "titolo_orig": "Hezbollah trascina il Libano in una nuova guerra",
        "testo_it": "Hezbollah trascina il Libano in guerra per sopravvivenza politica del movimento.",
        "priorita": "Alta",
        "id_gruppo": 1,
        "link": "https://www.limesonline.com/dossier/strillone-beirut-rassegna-mediorientale/hezbollah-libano-nella-guerra-in-iran-usa-israele-strategia-sopravvivenza-negoziati-21339315/",
        "orario": "15:14 - 3 Marzo",
        "timestamp": 1772547240.0,
        "contenuto_esteso": "L’uccisione di Khamenei ha spinto il Partito di Dio a schierarsi apertamente con il fronte iraniano. Il conflitto come strumento di sopravvivenza politica in uno Stato debole. Il movimento punta alla resistenza prolungata per sabotare i processi di normalizzazione regionale e possibili accordi del governo con Israele."
    },
    {
        "testata": "Limes",
        "lingua_originale": "it",
        "titolo_orig": "Logistica e obiettivi della guerra contro l'Iran",
        "testo_it": "Logistica e obiettivi: attacco USA-Israele essenziale per scopi in Medio Oriente.",
        "priorita": "Alta",
        "id_gruppo": 1,
        "link": "https://www.limesonline.com/articoli/obiettivi-e-logistica-guerra-preventiva-usa-israele-contro-iran-portaerei-missili-cambio-di-regime-21329896/",
        "orario": "15:49 - 3 Marzo",
        "timestamp": 1772549340.0,
        "contenuto_esteso": "La scelta di Usa e Israele di attaccare congiuntamente è essenziale per conseguire i rispettivi scopi in Medio Oriente. Il costoso schieramento militare americano e l’arsenale missilistico di Teheran. Russia e Cina protestano, ma non possono o non vogliono andare oltre."
    },
    {
        "testata": "Internazionale",
        "lingua_originale": "it",
        "titolo_orig": "Nuovi attacchi contro l’Iran, che rivendica il controllo dello stretto di Hormuz",
        "testo_it": "Nuovi attacchi a Iran; Teheran rivendica controllo Stretto di Hormuz, Israele avanza.",
        "priorita": "Alta",
        "id_gruppo": 1,
        "link": "https://www.internazionale.it/ultime-notizie/2026/03/04/iran-rivendica-controllo-stretto-hormuz",
        "orario": "12:28",
        "timestamp": 1772623715.0,
        "contenuto_esteso": "Il 4 marzo Israele e Stati Uniti hanno condotto nuovi attacchi contro l’Iran, Teheran ha rivendicato il “controllo totale” dello stretto di Hormuz e l’esercito israeliano ha intensificato la sua offensiva in Libano Leggi"
    },
    {
        "testata": "Internazionale",
        "lingua_originale": "it",
        "titolo_orig": "Il premier spagnolo Sánchez contesta la guerra in Iran e respinge le minacce di Trump",
        "testo_it": "Sánchez (Spagna) contesta guerra Iran e respinge minacce di Trump sulle basi.",
        "priorita": "Alta",
        "id_gruppo": 6,
        "link": "https://www.internazionale.it/ultime-notizie/2026/03/04/sanchez-contesta-guerra-iran-e-respinge-minacce-trump",
        "orario": "10:41",
        "timestamp": 1772617286.0,
        "contenuto_esteso": "“No alla guerra!”, ha risposto il primo ministro spagnolo Pedro Sánchez a Donald Trump, che l’aveva criticato per il rifiuto di autorizzare gli Stati Uniti a usare le basi militari in Andalusia per l’operazione militare contro l’Iran Leggi"
    },
    {
        "testata": "Il Manifesto",
        "lingua_originale": "it",
        "titolo_orig": "«Potrebbe arrivare un cattivo peggiore». Ma andiamo avanti",
        "testo_it": "Trump parla a Washington; a Teheran fosse comuni per 168 vittime, tra cui bambine.",
        "priorita": "Alta",
        "id_gruppo": 1,
        "link": "https://ilmanifesto.it/potrebbe-arrivare-un-cattivo-peggiore-ma-andiamo-avanti",
        "orario": "23:05 - 3 Marzo",
        "timestamp": 1772575553.0,
        "contenuto_esteso": "A Washington la giornata di dichiarazioni di Donald Trump si apre presto. Nelle stesse ore a Teheran le ruspe scavavano decine di fosse per seppellire le 168 bambine e insegnanti […] The post «Potrebbe arrivare un cattivo peggiore». Ma andiamo avanti first appeared on il manifesto ."
    },
    {
        "testata": "Il Manifesto",
        "lingua_originale": "it",
        "titolo_orig": "Bombardata l’assemblea che sostituiva Khamenei",
        "testo_it": "Bombardata l'assemblea che doveva sostituire Khamenei; il Paese non si è fermato.",
        "priorita": "Alta",
        "id_gruppo": 1,
        "link": "https://ilmanifesto.it/bombardata-lassemblea-che-sostituiva-khamenei",
        "orario": "23:05 - 3 Marzo",
        "timestamp": 1772575532.0,
        "contenuto_esteso": "«Siamo in contatto diretto con i governatori. Le circostanze sono particolari, ma il Paese non si è fermato. Sono in corso attività in tutto il Paese», scrive il presidente iraniano […] The post Bombardata l’assemblea che sostituiva Khamenei first appeared on il manifesto ."
    },
    {
        "testata": "Il Manifesto",
        "lingua_originale": "it",
        "titolo_orig": "Israele avanza in Libano. «Andremo in treno a Beirut»",
        "testo_it": "Israele avanza in Libano; sindaco Nahariya: \"Arriveremo a Beirut in treno\".",
        "priorita": "Alta",
        "id_gruppo": 1,
        "link": "https://ilmanifesto.it/israele-avanza-in-libano-andremo-in-treno-a-beirut",
        "orario": "23:05 - 3 Marzo",
        "timestamp": 1772575531.0,
        "contenuto_esteso": "«Abbiamo l’esercito più forte al mondo, ne sono orgoglioso. Arriveremo a Beirut in treno», prevede con ottimismo Ruben Marli, sindaco di Nahariya, a pochi chilometri dal confine con il Libano, […] The post Israele avanza in Libano. «Andremo in treno a Beirut» first appeared on il manifesto ."
    },
    {
        "testata": "Il Sole 24 Ore",
        "lingua_originale": "it",
        "titolo_orig": "Ue lancia l’Industrial Accelerator Act, il piano per rafforzare l’industria europea",
        "testo_it": "UE lancia Industrial Accelerator Act per rafforzare industria con criteri 'made in Europe'.",
        "priorita": "Media",
        "id_gruppo": 21,
        "link": "https://www.ilsole24ore.com/art/ue-lancia-l-industrial-accelerator-act-piano-rafforzare-l-industria-europea-AI6PSalB",
        "orario": "12:56",
        "timestamp": 1772625360.0,
        "contenuto_esteso": "Dopo diversi rinvii, la Commissione Europea propone l’Industrial Accelerator Act, una strategia per l’industria che fissa criteri di “made in Europe” e “basse emissioni di carbonio” per l’accesso ad appalti..."
    },
    {
        "testata": "Il Sole 24 Ore",
        "lingua_originale": "it",
        "titolo_orig": "Ucraina, droni di Kiev affondano nave russa nel Mediterraneo. Mosca: «Atto terroristico»",
        "testo_it": "Ucraina: droni affondano nave russa nel Mediterraneo; Mosca parla di terrorismo.",
        "priorita": "Media",
        "id_gruppo": 22,
        "link": "https://www.ilsole24ore.com/art/ucraina-droni-kiev-affondano-nave-russa-mediterraneo-mosca-atto-terroristico-AIlrOWlB",
        "orario": "12:18",
        "timestamp": 1772623092.0,
        "contenuto_esteso": "Mentre i negoziati sono in stallo, la guerra tra Ucraina e Russia continua sul campo e il confronto si espande anche nel Mediterraneo . Ieri sera una nave russa che trasportava..."
    },
    {
        "testata": "Il Sole 24 Ore",
        "lingua_originale": "it",
        "titolo_orig": "Texas, James Talarico vince le primarie democratiche",
        "testo_it": "Texas: James Talarico vince primarie democratiche per il Senato USA.",
        "priorita": "Bassa",
        "id_gruppo": 19,
        "link": "https://www.ilsole24ore.com/art/texas-james-talarico-vince-primarie-democratiche-AIWagKlB",
        "orario": "09:16",
        "timestamp": 1772612160.0,
        "contenuto_esteso": "James Talarico ha vinto le primarie democratiche per il Senato degli Stati Uniti in Texas, riuscendo a compiere una straordinaria ascesa da anonimo rappresentante statale a promettente figura..."
    }
];